// Copyright (c) 2025 Jonathan Fontanez
// SPDX-License-Identifier: BUSL-1.1

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use crate::error::{ResolverError, ResolverResult};
use crate::semver::SemVer;

/// `streamlib.lock` — content-hash-pinned resolved package set.
///
/// Wire shape: a single `version: 1` followed by a `packages` map keyed by
/// the canonical `"@org/name"` string. Each entry is the resolved
/// concrete location + content hash so a fresh checkout reconstructs the
/// same generated bindings byte-for-byte. `BTreeMap` (not `HashMap`)
/// keeps the lockfile diff-stable across regenerations.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Lockfile {
    /// Lockfile schema version. Currently `1`.
    pub version: u32,

    pub packages: BTreeMap<String, LockfileEntry>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LockfileEntry {
    pub version: SemVer,
    pub source: LockfileSource,
    /// Content hash of the resolved package contents (typically sha256:hex).
    /// Includes the namespacing prefix so future hash algorithms can land
    /// without breaking lockfile parsing.
    pub content_hash: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum LockfileSource {
    Registry { url: String },
    Path { path: PathBuf },
    Git { url: String, rev: String },
}

/// Conventional file name for the **codegen** lockfile — the schema-input
/// reproducibility pin written next to a `streamlib.yaml` by
/// `streamlib generate` / jtd-codegen. Distinct lifecycle from the
/// application lockfile ([`APP_LOCKFILE_NAME`]): codegen pins the
/// *schema* set that reconstructs generated bindings byte-for-byte,
/// whereas the app lockfile pins the *runtime package* set an installed
/// application loads offline.
pub const LOCKFILE_NAME: &str = "streamlib.lock";

/// Conventional file name for the **application** lockfile — the runtime
/// package pin set written by `streamlib install` and consumed by a
/// locked run (`Runner::add_modules_from_lockfile`). Shares the on-disk
/// [`Lockfile`] wire shape with the codegen lockfile ([`LOCKFILE_NAME`])
/// but is a distinct file with a distinct lifecycle — the app lockfile is
/// what a deploy ships and what makes an offline run reproducible.
pub const APP_LOCKFILE_NAME: &str = "streamlib-app.lock";

/// Compute the content hash of a package: SHA-256 over the manifest body
/// plus every schema YAML keyed by relative path.
///
/// `schemas` is `(relative_path, content)` pairs. The function sorts by path
/// before hashing so the result is stable regardless of caller order.
pub fn compute_content_hash(manifest_body: &str, schemas: &[(String, String)]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(b"streamlib-package-content-hash-v1\n");
    hasher.update(b"manifest:\n");
    hasher.update(manifest_body.as_bytes());
    hasher.update(b"\n");

    let mut sorted: Vec<&(String, String)> = schemas.iter().collect();
    sorted.sort_by(|a, b| a.0.cmp(&b.0));
    for (path, content) in sorted {
        hasher.update(b"schema:");
        hasher.update(path.as_bytes());
        hasher.update(b"\n");
        hasher.update(content.as_bytes());
        hasher.update(b"\n");
    }

    let digest = hasher.finalize();
    format!("sha256:{:x}", digest)
}

/// SHA-256 over an arbitrary byte slice, namespace-prefixed `sha256:`. Used
/// for one-off content hashing where caller supplies an already-canonical
/// representation.
pub fn hash_content(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    format!("sha256:{:x}", hasher.finalize())
}

/// Codegen-lockfile header (schema-input reproducibility pin).
const CODEGEN_LOCKFILE_HEADER: &str = "\
# Copyright (c) 2025 Jonathan Fontanez
# SPDX-License-Identifier: BUSL-1.1
#
# AUTOGENERATED BY `streamlib generate`. DO NOT EDIT BY HAND.
#
# This lockfile pins resolved package versions + content hashes so a fresh
# checkout reconstructs the same generated bindings byte-for-byte.
# Commit it in applications and examples; don't commit it in publishable
# libraries (they inherit their consumer's lock).
";

/// Application-lockfile header (runtime package pin set).
const APP_LOCKFILE_HEADER: &str = "\
# Copyright (c) 2025 Jonathan Fontanez
# SPDX-License-Identifier: BUSL-1.1
#
# AUTOGENERATED BY `streamlib install`. DO NOT EDIT BY HAND.
#
# This lockfile pins the exact resolved package versions + content hashes
# an installed application loads. A locked run
# (`Runner::add_modules_from_lockfile`) consumes it strictly from the
# installed package cache and performs NO live re-resolution — so the run
# works offline and is byte-reproducible. Commit it in applications and
# examples; a deploy ships it.
";

/// Write a [`Lockfile`] to disk as YAML behind `header`. The wire shape is
/// identical regardless of header; only the leading comment block differs.
fn write_lockfile_with_header(
    path: &Path,
    lockfile: &Lockfile,
    header: &str,
) -> ResolverResult<()> {
    let body =
        serde_yaml::to_string(lockfile).map_err(|e| ResolverError::ManifestParse {
            path: path.to_path_buf(),
            source: e,
        })?;
    let mut out = String::with_capacity(header.len() + body.len());
    out.push_str(header);
    out.push_str(&body);
    std::fs::write(path, out).map_err(|e| ResolverError::Io {
        path: path.to_path_buf(),
        source: e,
    })?;
    Ok(())
}

/// Write the **codegen** lockfile ([`LOCKFILE_NAME`]) to disk as YAML.
pub fn write_lockfile(path: &Path, lockfile: &Lockfile) -> ResolverResult<()> {
    write_lockfile_with_header(path, lockfile, CODEGEN_LOCKFILE_HEADER)
}

/// Write the **application** lockfile ([`APP_LOCKFILE_NAME`]) to disk as
/// YAML. Same wire shape as [`write_lockfile`]; distinct header + file.
pub fn write_app_lockfile(path: &Path, lockfile: &Lockfile) -> ResolverResult<()> {
    write_lockfile_with_header(path, lockfile, APP_LOCKFILE_HEADER)
}

/// Read a lockfile from disk.
pub fn read_lockfile(path: &Path) -> ResolverResult<Lockfile> {
    let content = std::fs::read_to_string(path).map_err(|e| ResolverError::ManifestRead {
        path: path.to_path_buf(),
        source: e,
    })?;
    serde_yaml::from_str(&content).map_err(|e| ResolverError::ManifestParse {
        path: path.to_path_buf(),
        source: e,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lockfile_round_trip() {
        let yaml = r#"
version: 1
packages:
  "@tatolab/core":
    version: 1.0.0
    source:
      kind: registry
      url: https://packages.streamlib.dev
    content_hash: "sha256:0123456789abcdef"
  "@tatolab/h264":
    version: 0.4.2
    source:
      kind: path
      path: ../h264
    content_hash: "sha256:fedcba9876543210"
  "@tatolab/moq":
    version: 0.2.0
    source:
      kind: git
      url: https://github.com/tatolab/moq
      rev: abc123def456
    content_hash: "sha256:1111222233334444"
  "@tatolab/camera":
    version: 0.4.33-dev.2
    source:
      kind: registry
      url: https://packages.streamlib.dev
    content_hash: "sha256:5555666677778888"
"#;
        let lock: Lockfile = serde_yaml::from_str(yaml).unwrap();
        assert_eq!(lock.version, 1);
        assert_eq!(lock.packages.len(), 4);

        let core = lock.packages.get("@tatolab/core").unwrap();
        assert_eq!(core.version, SemVer::new(1, 0, 0));
        assert!(matches!(core.source, LockfileSource::Registry { .. }));

        let h264 = lock.packages.get("@tatolab/h264").unwrap();
        assert!(matches!(h264.source, LockfileSource::Path { .. }));

        let moq = lock.packages.get("@tatolab/moq").unwrap();
        match &moq.source {
            LockfileSource::Git { url, rev } => {
                assert_eq!(url, "https://github.com/tatolab/moq");
                assert_eq!(rev, "abc123def456");
            }
            other => panic!("expected Git source, got {:?}", other),
        }

        // A prerelease package version survives the lockfile round-trip.
        use crate::semver::PrereleaseKind;
        let camera = lock.packages.get("@tatolab/camera").unwrap();
        assert_eq!(
            camera.version,
            SemVer::new_prerelease(0, 4, 33, PrereleaseKind::Dev, 2)
        );

        let s = serde_yaml::to_string(&lock).unwrap();
        assert!(s.contains("0.4.33-dev.2"), "serialized: {s}");
        let back: Lockfile = serde_yaml::from_str(&s).unwrap();
        assert_eq!(back.packages.len(), 4);
        assert_eq!(
            back.packages.get("@tatolab/camera").unwrap().version,
            SemVer::new_prerelease(0, 4, 33, PrereleaseKind::Dev, 2)
        );
    }

    #[test]
    fn lockfile_rejects_unknown_source_kind() {
        let yaml = r#"
version: 1
packages:
  "@tatolab/core":
    version: 1.0.0
    source:
      kind: ftp
      url: ftp://example.com
    content_hash: "sha256:abcd"
"#;
        let res: Result<Lockfile, _> = serde_yaml::from_str(yaml);
        assert!(res.is_err());
    }

    #[test]
    fn lockfile_keys_are_diff_stable() {
        let mut a = Lockfile {
            version: 1,
            packages: BTreeMap::new(),
        };
        a.packages.insert(
            "@tatolab/zzz".into(),
            LockfileEntry {
                version: SemVer::new(1, 0, 0),
                source: LockfileSource::Path { path: "z".into() },
                content_hash: "sha256:1".into(),
            },
        );
        a.packages.insert(
            "@tatolab/aaa".into(),
            LockfileEntry {
                version: SemVer::new(1, 0, 0),
                source: LockfileSource::Path { path: "a".into() },
                content_hash: "sha256:2".into(),
            },
        );

        let yaml_a = serde_yaml::to_string(&a).unwrap();
        let aaa_pos = yaml_a.find("@tatolab/aaa").unwrap();
        let zzz_pos = yaml_a.find("@tatolab/zzz").unwrap();
        assert!(aaa_pos < zzz_pos, "BTreeMap must produce sorted output");
    }

    #[test]
    fn content_hash_is_deterministic_across_input_orders() {
        let manifest = "package:\n  org: tatolab\n  name: core\n  version: 1.0.0\n";
        let schemas_a = vec![
            ("schemas/a.yaml".into(), "type: a\n".into()),
            ("schemas/b.yaml".into(), "type: b\n".into()),
        ];
        let schemas_b = vec![
            ("schemas/b.yaml".into(), "type: b\n".into()),
            ("schemas/a.yaml".into(), "type: a\n".into()),
        ];
        let h1 = compute_content_hash(manifest, &schemas_a);
        let h2 = compute_content_hash(manifest, &schemas_b);
        assert_eq!(h1, h2, "input order must not affect content hash");
        assert!(h1.starts_with("sha256:"));
    }

    #[test]
    fn content_hash_changes_on_manifest_change() {
        let m1 = "package:\n  org: tatolab\n  name: core\n  version: 1.0.0\n";
        let m2 = "package:\n  org: tatolab\n  name: core\n  version: 1.0.1\n";
        let schemas: Vec<(String, String)> = vec![];
        let h1 = compute_content_hash(m1, &schemas);
        let h2 = compute_content_hash(m2, &schemas);
        assert_ne!(h1, h2);
    }

    #[test]
    fn content_hash_changes_on_schema_change() {
        let manifest = "package:\n  org: tatolab\n  name: core\n  version: 1.0.0\n";
        let s1 = vec![("schemas/a.yaml".into(), "type: a\n".into())];
        let s2 = vec![("schemas/a.yaml".into(), "type: A\n".into())];
        let h1 = compute_content_hash(manifest, &s1);
        let h2 = compute_content_hash(manifest, &s2);
        assert_ne!(h1, h2);
    }

    #[test]
    fn write_and_read_lockfile_round_trip() {
        let tmp = tempfile::tempdir().unwrap();
        let mut lock = Lockfile {
            version: 1,
            packages: BTreeMap::new(),
        };
        lock.packages.insert(
            "@tatolab/core".into(),
            LockfileEntry {
                version: SemVer::new(1, 0, 0),
                source: LockfileSource::Path { path: "../core".into() },
                content_hash: "sha256:abc".into(),
            },
        );

        let path = tmp.path().join("streamlib.lock");
        write_lockfile(&path, &lock).unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("AUTOGENERATED"));

        let back = read_lockfile(&path).unwrap();
        assert_eq!(back.version, 1);
        assert_eq!(back.packages.len(), 1);
    }

    #[test]
    fn app_lockfile_shares_wire_shape_but_distinct_header() {
        // The app lockfile reuses the `Lockfile` wire shape (round-trips
        // through `read_lockfile`) but carries a distinct, install-scoped
        // header — the codegen-vs-app split. Two writes are byte-identical.
        let tmp = tempfile::tempdir().unwrap();
        let mut lock = Lockfile {
            version: 1,
            packages: BTreeMap::new(),
        };
        lock.packages.insert(
            "@tatolab/core".into(),
            LockfileEntry {
                version: SemVer::new(1, 0, 0),
                source: LockfileSource::Registry {
                    url: "file:///m".into(),
                },
                content_hash: "sha256:abc".into(),
            },
        );

        let app = tmp.path().join("streamlib-app.lock");
        let codegen = tmp.path().join("streamlib.lock");
        write_app_lockfile(&app, &lock).unwrap();
        write_lockfile(&codegen, &lock).unwrap();

        let app_body = std::fs::read_to_string(&app).unwrap();
        let codegen_body = std::fs::read_to_string(&codegen).unwrap();
        assert!(app_body.contains("streamlib install"), "app header: {app_body}");
        assert!(
            codegen_body.contains("streamlib generate"),
            "codegen header: {codegen_body}"
        );
        assert_ne!(app_body, codegen_body, "headers must differ");

        // The wire payload (below the header) round-trips identically.
        let back = read_lockfile(&app).unwrap();
        assert_eq!(back.packages.len(), 1);
        assert_eq!(back.packages.get("@tatolab/core").unwrap().version, SemVer::new(1, 0, 0));

        // Byte-determinism: a second write of the same lockfile is identical.
        let app2 = tmp.path().join("streamlib-app-2.lock");
        write_app_lockfile(&app2, &lock).unwrap();
        assert_eq!(std::fs::read(&app).unwrap(), std::fs::read(&app2).unwrap());
    }

    #[test]
    fn write_lockfile_byte_identical_for_same_input() {
        // Two writes from the same Lockfile must produce byte-identical files.
        let tmp = tempfile::tempdir().unwrap();
        let lock = Lockfile {
            version: 1,
            packages: BTreeMap::new(),
        };
        let p1 = tmp.path().join("a.lock");
        let p2 = tmp.path().join("b.lock");
        write_lockfile(&p1, &lock).unwrap();
        write_lockfile(&p2, &lock).unwrap();
        let a = std::fs::read(&p1).unwrap();
        let b = std::fs::read(&p2).unwrap();
        assert_eq!(a, b);
    }
}
