// Copyright (c) 2025 Jonathan Fontanez
// SPDX-License-Identifier: BUSL-1.1

// This file is @generated by prost-build.
/// A single span record matching the SQLite spans table schema.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TelemetrySpanRecord {
    #[prost(string, tag = "1")]
    pub trace_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub span_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub parent_span_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub operation_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub service_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub span_kind: ::prost::alloc::string::String,
    #[prost(int64, tag = "7")]
    pub start_time_unix_ns: i64,
    #[prost(int64, tag = "8")]
    pub end_time_unix_ns: i64,
    #[prost(int64, tag = "9")]
    pub duration_ns: i64,
    #[prost(string, tag = "10")]
    pub status_code: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub status_message: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub attributes_json: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub resource_json: ::prost::alloc::string::String,
    #[prost(string, tag = "14")]
    pub events_json: ::prost::alloc::string::String,
}
/// A single log record matching the SQLite logs table schema.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TelemetryLogRecord {
    #[prost(int64, tag = "1")]
    pub timestamp_unix_ns: i64,
    #[prost(string, tag = "2")]
    pub trace_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub span_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub severity_number: i32,
    #[prost(string, tag = "5")]
    pub severity_text: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub body: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub service_name: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub attributes_json: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub resource_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IngestTelemetryRequest {
    #[prost(message, repeated, tag = "1")]
    pub spans: ::prost::alloc::vec::Vec<TelemetrySpanRecord>,
    #[prost(message, repeated, tag = "2")]
    pub logs: ::prost::alloc::vec::Vec<TelemetryLogRecord>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct IngestTelemetryResponse {
    #[prost(int32, tag = "1")]
    pub accepted_spans: i32,
    #[prost(int32, tag = "2")]
    pub accepted_logs: i32,
}
/// Generated client implementations.
pub mod telemetry_ingest_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Telemetry ingestion service — runtimes send spans and logs to the broker.
    #[derive(Debug, Clone)]
    pub struct TelemetryIngestServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl TelemetryIngestServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> TelemetryIngestServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> TelemetryIngestServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            TelemetryIngestServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Ingest a batch of spans and/or logs.
        pub async fn ingest_telemetry(
            &mut self,
            request: impl tonic::IntoRequest<super::IngestTelemetryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::IngestTelemetryResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/streamlib.telemetry.TelemetryIngestService/IngestTelemetry",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "streamlib.telemetry.TelemetryIngestService",
                        "IngestTelemetry",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod telemetry_ingest_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with TelemetryIngestServiceServer.
    #[async_trait]
    pub trait TelemetryIngestService: std::marker::Send + std::marker::Sync + 'static {
        /// Ingest a batch of spans and/or logs.
        async fn ingest_telemetry(
            &self,
            request: tonic::Request<super::IngestTelemetryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::IngestTelemetryResponse>,
            tonic::Status,
        >;
    }
    /// Telemetry ingestion service — runtimes send spans and logs to the broker.
    #[derive(Debug)]
    pub struct TelemetryIngestServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> TelemetryIngestServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for TelemetryIngestServiceServer<T>
    where
        T: TelemetryIngestService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/streamlib.telemetry.TelemetryIngestService/IngestTelemetry" => {
                    #[allow(non_camel_case_types)]
                    struct IngestTelemetrySvc<T: TelemetryIngestService>(pub Arc<T>);
                    impl<
                        T: TelemetryIngestService,
                    > tonic::server::UnaryService<super::IngestTelemetryRequest>
                    for IngestTelemetrySvc<T> {
                        type Response = super::IngestTelemetryResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::IngestTelemetryRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TelemetryIngestService>::ingest_telemetry(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = IngestTelemetrySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for TelemetryIngestServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "streamlib.telemetry.TelemetryIngestService";
    impl<T> tonic::server::NamedService for TelemetryIngestServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
