# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import broker_pb2 as broker__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in broker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrokerServiceStub(object):
    """BrokerService provides diagnostics and monitoring for the XPC broker.
    Used by CLI tools to inspect broker state without affecting frame transfer.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealth = channel.unary_unary(
                '/streamlib.broker.BrokerService/GetHealth',
                request_serializer=broker__pb2.GetHealthRequest.SerializeToString,
                response_deserializer=broker__pb2.GetHealthResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/streamlib.broker.BrokerService/GetVersion',
                request_serializer=broker__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=broker__pb2.GetVersionResponse.FromString,
                _registered_method=True)
        self.ListRuntimes = channel.unary_unary(
                '/streamlib.broker.BrokerService/ListRuntimes',
                request_serializer=broker__pb2.ListRuntimesRequest.SerializeToString,
                response_deserializer=broker__pb2.ListRuntimesResponse.FromString,
                _registered_method=True)
        self.ListProcessors = channel.unary_unary(
                '/streamlib.broker.BrokerService/ListProcessors',
                request_serializer=broker__pb2.ListProcessorsRequest.SerializeToString,
                response_deserializer=broker__pb2.ListProcessorsResponse.FromString,
                _registered_method=True)
        self.ListConnections = channel.unary_unary(
                '/streamlib.broker.BrokerService/ListConnections',
                request_serializer=broker__pb2.ListConnectionsRequest.SerializeToString,
                response_deserializer=broker__pb2.ListConnectionsResponse.FromString,
                _registered_method=True)
        self.GetRuntimeEndpoint = channel.unary_unary(
                '/streamlib.broker.BrokerService/GetRuntimeEndpoint',
                request_serializer=broker__pb2.GetRuntimeEndpointRequest.SerializeToString,
                response_deserializer=broker__pb2.GetRuntimeEndpointResponse.FromString,
                _registered_method=True)
        self.RegisterRuntime = channel.unary_unary(
                '/streamlib.broker.BrokerService/RegisterRuntime',
                request_serializer=broker__pb2.RegisterRuntimeRequest.SerializeToString,
                response_deserializer=broker__pb2.RegisterRuntimeResponse.FromString,
                _registered_method=True)
        self.UnregisterRuntime = channel.unary_unary(
                '/streamlib.broker.BrokerService/UnregisterRuntime',
                request_serializer=broker__pb2.UnregisterRuntimeRequest.SerializeToString,
                response_deserializer=broker__pb2.UnregisterRuntimeResponse.FromString,
                _registered_method=True)
        self.PruneDeadRuntimes = channel.unary_unary(
                '/streamlib.broker.BrokerService/PruneDeadRuntimes',
                request_serializer=broker__pb2.PruneDeadRuntimesRequest.SerializeToString,
                response_deserializer=broker__pb2.PruneDeadRuntimesResponse.FromString,
                _registered_method=True)
        self.AllocateConnection = channel.unary_unary(
                '/streamlib.broker.BrokerService/AllocateConnection',
                request_serializer=broker__pb2.AllocateConnectionRequest.SerializeToString,
                response_deserializer=broker__pb2.AllocateConnectionResponse.FromString,
                _registered_method=True)
        self.HostAlive = channel.unary_unary(
                '/streamlib.broker.BrokerService/HostAlive',
                request_serializer=broker__pb2.HostAliveRequest.SerializeToString,
                response_deserializer=broker__pb2.HostAliveResponse.FromString,
                _registered_method=True)
        self.HostXpcReady = channel.unary_unary(
                '/streamlib.broker.BrokerService/HostXpcReady',
                request_serializer=broker__pb2.HostXpcReadyRequest.SerializeToString,
                response_deserializer=broker__pb2.HostXpcReadyResponse.FromString,
                _registered_method=True)
        self.ClientAlive = channel.unary_unary(
                '/streamlib.broker.BrokerService/ClientAlive',
                request_serializer=broker__pb2.ClientAliveRequest.SerializeToString,
                response_deserializer=broker__pb2.ClientAliveResponse.FromString,
                _registered_method=True)
        self.GetClientStatus = channel.unary_unary(
                '/streamlib.broker.BrokerService/GetClientStatus',
                request_serializer=broker__pb2.GetClientStatusRequest.SerializeToString,
                response_deserializer=broker__pb2.GetClientStatusResponse.FromString,
                _registered_method=True)
        self.GetHostStatus = channel.unary_unary(
                '/streamlib.broker.BrokerService/GetHostStatus',
                request_serializer=broker__pb2.GetHostStatusRequest.SerializeToString,
                response_deserializer=broker__pb2.GetHostStatusResponse.FromString,
                _registered_method=True)
        self.MarkAcked = channel.unary_unary(
                '/streamlib.broker.BrokerService/MarkAcked',
                request_serializer=broker__pb2.MarkAckedRequest.SerializeToString,
                response_deserializer=broker__pb2.MarkAckedResponse.FromString,
                _registered_method=True)
        self.GetConnectionInfo = channel.unary_unary(
                '/streamlib.broker.BrokerService/GetConnectionInfo',
                request_serializer=broker__pb2.GetConnectionInfoRequest.SerializeToString,
                response_deserializer=broker__pb2.GetConnectionInfoResponse.FromString,
                _registered_method=True)
        self.CloseConnection = channel.unary_unary(
                '/streamlib.broker.BrokerService/CloseConnection',
                request_serializer=broker__pb2.CloseConnectionRequest.SerializeToString,
                response_deserializer=broker__pb2.CloseConnectionResponse.FromString,
                _registered_method=True)


class BrokerServiceServicer(object):
    """BrokerService provides diagnostics and monitoring for the XPC broker.
    Used by CLI tools to inspect broker state without affecting frame transfer.
    """

    def GetHealth(self, request, context):
        """Health check - verify broker is responsive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Version info - get broker version and build info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuntimes(self, request, context):
        """List all registered runtimes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProcessors(self, request, context):
        """List processors for a specific runtime
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConnections(self, request, context):
        """List active XPC connections
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeEndpoint(self, request, context):
        """Get runtime endpoint by name or ID (DNS-like lookup)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterRuntime(self, request, context):
        """Register a runtime (called by runtime on startup)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterRuntime(self, request, context):
        """Unregister a runtime (called by runtime on shutdown)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PruneDeadRuntimes(self, request, context):
        """Prune dead runtimes (removes runtimes whose PIDs no longer exist)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllocateConnection(self, request, context):
        """─────────────────────────────────────────────────────────────────────────────
        XPC Bridge Connection Management (Phase 4)
        ─────────────────────────────────────────────────────────────────────────────

        Host processor allocates a connection before spawning subprocess
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HostAlive(self, request, context):
        """Host reports alive (Rust code is running)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HostXpcReady(self, request, context):
        """Host confirms XPC endpoint was stored (called AFTER XPC store_endpoint)
        NOTE: The actual endpoint is transferred via XPC, not gRPC (Mach ports can't serialize)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientAlive(self, request, context):
        """Subprocess reports alive (first contact with broker)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClientStatus(self, request, context):
        """Host polls for client status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHostStatus(self, request, context):
        """Client polls for host status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkAcked(self, request, context):
        """Either side marks their ACK complete
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnectionInfo(self, request, context):
        """Get full connection info (for debugging)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseConnection(self, request, context):
        """Called by host processor on teardown to release broker resources
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrokerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=broker__pb2.GetHealthRequest.FromString,
                    response_serializer=broker__pb2.GetHealthResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=broker__pb2.GetVersionRequest.FromString,
                    response_serializer=broker__pb2.GetVersionResponse.SerializeToString,
            ),
            'ListRuntimes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuntimes,
                    request_deserializer=broker__pb2.ListRuntimesRequest.FromString,
                    response_serializer=broker__pb2.ListRuntimesResponse.SerializeToString,
            ),
            'ListProcessors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProcessors,
                    request_deserializer=broker__pb2.ListProcessorsRequest.FromString,
                    response_serializer=broker__pb2.ListProcessorsResponse.SerializeToString,
            ),
            'ListConnections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConnections,
                    request_deserializer=broker__pb2.ListConnectionsRequest.FromString,
                    response_serializer=broker__pb2.ListConnectionsResponse.SerializeToString,
            ),
            'GetRuntimeEndpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeEndpoint,
                    request_deserializer=broker__pb2.GetRuntimeEndpointRequest.FromString,
                    response_serializer=broker__pb2.GetRuntimeEndpointResponse.SerializeToString,
            ),
            'RegisterRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterRuntime,
                    request_deserializer=broker__pb2.RegisterRuntimeRequest.FromString,
                    response_serializer=broker__pb2.RegisterRuntimeResponse.SerializeToString,
            ),
            'UnregisterRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterRuntime,
                    request_deserializer=broker__pb2.UnregisterRuntimeRequest.FromString,
                    response_serializer=broker__pb2.UnregisterRuntimeResponse.SerializeToString,
            ),
            'PruneDeadRuntimes': grpc.unary_unary_rpc_method_handler(
                    servicer.PruneDeadRuntimes,
                    request_deserializer=broker__pb2.PruneDeadRuntimesRequest.FromString,
                    response_serializer=broker__pb2.PruneDeadRuntimesResponse.SerializeToString,
            ),
            'AllocateConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocateConnection,
                    request_deserializer=broker__pb2.AllocateConnectionRequest.FromString,
                    response_serializer=broker__pb2.AllocateConnectionResponse.SerializeToString,
            ),
            'HostAlive': grpc.unary_unary_rpc_method_handler(
                    servicer.HostAlive,
                    request_deserializer=broker__pb2.HostAliveRequest.FromString,
                    response_serializer=broker__pb2.HostAliveResponse.SerializeToString,
            ),
            'HostXpcReady': grpc.unary_unary_rpc_method_handler(
                    servicer.HostXpcReady,
                    request_deserializer=broker__pb2.HostXpcReadyRequest.FromString,
                    response_serializer=broker__pb2.HostXpcReadyResponse.SerializeToString,
            ),
            'ClientAlive': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientAlive,
                    request_deserializer=broker__pb2.ClientAliveRequest.FromString,
                    response_serializer=broker__pb2.ClientAliveResponse.SerializeToString,
            ),
            'GetClientStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClientStatus,
                    request_deserializer=broker__pb2.GetClientStatusRequest.FromString,
                    response_serializer=broker__pb2.GetClientStatusResponse.SerializeToString,
            ),
            'GetHostStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHostStatus,
                    request_deserializer=broker__pb2.GetHostStatusRequest.FromString,
                    response_serializer=broker__pb2.GetHostStatusResponse.SerializeToString,
            ),
            'MarkAcked': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkAcked,
                    request_deserializer=broker__pb2.MarkAckedRequest.FromString,
                    response_serializer=broker__pb2.MarkAckedResponse.SerializeToString,
            ),
            'GetConnectionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnectionInfo,
                    request_deserializer=broker__pb2.GetConnectionInfoRequest.FromString,
                    response_serializer=broker__pb2.GetConnectionInfoResponse.SerializeToString,
            ),
            'CloseConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseConnection,
                    request_deserializer=broker__pb2.CloseConnectionRequest.FromString,
                    response_serializer=broker__pb2.CloseConnectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streamlib.broker.BrokerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streamlib.broker.BrokerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrokerService(object):
    """BrokerService provides diagnostics and monitoring for the XPC broker.
    Used by CLI tools to inspect broker state without affecting frame transfer.
    """

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamlib.broker.BrokerService/GetHealth',
            broker__pb2.GetHealthRequest.SerializeToString,
            broker__pb2.GetHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamlib.broker.BrokerService/GetVersion',
            broker__pb2.GetVersionRequest.SerializeToString,
            broker__pb2.GetVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuntimes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamlib.broker.BrokerService/ListRuntimes',
            broker__pb2.ListRuntimesRequest.SerializeToString,
            broker__pb2.ListRuntimesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProcessors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamlib.broker.BrokerService/ListProcessors',
            broker__pb2.ListProcessorsRequest.SerializeToString,
            broker__pb2.ListProcessorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConnections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamlib.broker.BrokerService/ListConnections',
            broker__pb2.ListConnectionsRequest.SerializeToString,
            broker__pb2.ListConnectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntimeEndpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamlib.broker.BrokerService/GetRuntimeEndpoint',
            broker__pb2.GetRuntimeEndpointRequest.SerializeToString,
            broker__pb2.GetRuntimeEndpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamlib.broker.BrokerService/RegisterRuntime',
            broker__pb2.RegisterRuntimeRequest.SerializeToString,
            broker__pb2.RegisterRuntimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamlib.broker.BrokerService/UnregisterRuntime',
            broker__pb2.UnregisterRuntimeRequest.SerializeToString,
            broker__pb2.UnregisterRuntimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PruneDeadRuntimes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamlib.broker.BrokerService/PruneDeadRuntimes',
            broker__pb2.PruneDeadRuntimesRequest.SerializeToString,
            broker__pb2.PruneDeadRuntimesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllocateConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamlib.broker.BrokerService/AllocateConnection',
            broker__pb2.AllocateConnectionRequest.SerializeToString,
            broker__pb2.AllocateConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HostAlive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamlib.broker.BrokerService/HostAlive',
            broker__pb2.HostAliveRequest.SerializeToString,
            broker__pb2.HostAliveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HostXpcReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamlib.broker.BrokerService/HostXpcReady',
            broker__pb2.HostXpcReadyRequest.SerializeToString,
            broker__pb2.HostXpcReadyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientAlive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamlib.broker.BrokerService/ClientAlive',
            broker__pb2.ClientAliveRequest.SerializeToString,
            broker__pb2.ClientAliveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClientStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamlib.broker.BrokerService/GetClientStatus',
            broker__pb2.GetClientStatusRequest.SerializeToString,
            broker__pb2.GetClientStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHostStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamlib.broker.BrokerService/GetHostStatus',
            broker__pb2.GetHostStatusRequest.SerializeToString,
            broker__pb2.GetHostStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkAcked(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamlib.broker.BrokerService/MarkAcked',
            broker__pb2.MarkAckedRequest.SerializeToString,
            broker__pb2.MarkAckedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnectionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamlib.broker.BrokerService/GetConnectionInfo',
            broker__pb2.GetConnectionInfoRequest.SerializeToString,
            broker__pb2.GetConnectionInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streamlib.broker.BrokerService/CloseConnection',
            broker__pb2.CloseConnectionRequest.SerializeToString,
            broker__pb2.CloseConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
