#!/usr/bin/env bash
# Copyright (c) 2025 Jonathan Fontanez
# SPDX-License-Identifier: BUSL-1.1
#
# Generate test fixture files for the nvpro-vulkan-video test suite.
#
# All encoded fixtures MUST be generated by ffmpeg software encoders
# (libx264, libx265) — never hardware/Vulkan encoders. These files are
# "known good" reference inputs for isolated decode testing. Using our
# own encoder to generate decode test inputs defeats the purpose.
#
# Requires: ffmpeg with libx264 and libx265 (software encoders).
#   On Ubuntu, the system ffmpeg may lack these. Use a static build:
#   https://johnvansickle.com/ffmpeg/
#   Set FFMPEG=/path/to/static/ffmpeg before running this script.
#
# Outputs (4 files):
#   1. testsrc2_640x480_nv12.yuv  — 10s raw NV12 source (encoder input)
#   2. testsrc2_640x480_bgra.raw  — 10s raw BGRA source (RGBA encode path)
#   3. testsrc2_640x480.h264      — H.264 encoded by libx264 (decode test input)
#   4. testsrc2_640x480.h265      — H.265 encoded by libx265 (decode test input)
#
# Usage:
#   ./tests/generate_fixtures.sh            # generate all fixtures
#   ./tests/generate_fixtures.sh --clean    # remove generated fixtures

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
FIXTURE_DIR="$SCRIPT_DIR/fixtures"

WIDTH=640
HEIGHT=480
FPS=30
DURATION=10  # seconds
FRAMES=$((FPS * DURATION))

# Use FFMPEG env var if set, otherwise default to system ffmpeg
FFMPEG="${FFMPEG:-ffmpeg}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

log_pass() { echo -e "  ${GREEN}[PASS]${NC} $1"; }
log_fail() { echo -e "  ${RED}[FAIL]${NC} $1"; exit 1; }
log_info() { echo -e "  ${YELLOW}[INFO]${NC} $1"; }

# --- Clean mode ---
if [[ "${1:-}" == "--clean" ]]; then
    echo "Cleaning fixtures..."
    rm -f "$FIXTURE_DIR"/*.yuv "$FIXTURE_DIR"/*.raw \
          "$FIXTURE_DIR"/*.h264 "$FIXTURE_DIR"/*.h265 \
          "$FIXTURE_DIR"/*.ivf "$FIXTURE_DIR"/*.png "$FIXTURE_DIR"/*.mp4
    echo "Done."
    exit 0
fi

# --- Check ffmpeg and required encoders ---
if ! command -v "$FFMPEG" &>/dev/null; then
    echo "ffmpeg not found at '$FFMPEG'."
    echo "Set FFMPEG=/path/to/ffmpeg with libx264/libx265 support."
    exit 1
fi

HAS_X264=$("$FFMPEG" -encoders 2>&1 | grep -c "libx264 " || true)
HAS_X265=$("$FFMPEG" -encoders 2>&1 | grep -c "libx265 " || true)

if [[ "$HAS_X264" -eq 0 ]] || [[ "$HAS_X265" -eq 0 ]]; then
    echo "ERROR: ffmpeg at '$FFMPEG' is missing required software encoders."
    [[ "$HAS_X264" -eq 0 ]] && echo "  Missing: libx264"
    [[ "$HAS_X265" -eq 0 ]] && echo "  Missing: libx265"
    echo ""
    echo "Download a static build with full codec support:"
    echo "  https://johnvansickle.com/ffmpeg/"
    echo "Then run: FFMPEG=/path/to/ffmpeg ./tests/generate_fixtures.sh"
    exit 1
fi

echo "=== Generating Test Fixtures ==="
echo "    ffmpeg:     $FFMPEG"
echo "    Resolution: ${WIDTH}x${HEIGHT}"
echo "    Duration:   ${DURATION}s (${FRAMES} frames @ ${FPS} fps)"
echo ""

# --- 1. Raw NV12 source (testsrc2 with motion) ---
echo "[1/4] Raw NV12 source frames (testsrc2)"
NV12_FILE="$FIXTURE_DIR/testsrc2_${WIDTH}x${HEIGHT}_nv12.yuv"
"$FFMPEG" -y -f lavfi \
    -i "testsrc2=size=${WIDTH}x${HEIGHT}:rate=${FPS}:duration=${DURATION}" \
    -frames:v "$FRAMES" -pix_fmt nv12 \
    "$NV12_FILE" 2>/dev/null
EXPECTED_SIZE=$((WIDTH * HEIGHT * 3 / 2 * FRAMES))
ACTUAL_SIZE=$(stat -c%s "$NV12_FILE" 2>/dev/null || stat -f%z "$NV12_FILE" 2>/dev/null)
if [[ "$ACTUAL_SIZE" -eq "$EXPECTED_SIZE" ]]; then
    log_pass "$NV12_FILE ($ACTUAL_SIZE bytes, $FRAMES frames)"
else
    log_fail "Size mismatch: expected $EXPECTED_SIZE, got $ACTUAL_SIZE"
fi

# --- 2. Raw BGRA source (same content, for RGBA encode path) ---
echo ""
echo "[2/4] Raw BGRA source frames (testsrc2)"
BGRA_FILE="$FIXTURE_DIR/testsrc2_${WIDTH}x${HEIGHT}_bgra.raw"
"$FFMPEG" -y -f lavfi \
    -i "testsrc2=size=${WIDTH}x${HEIGHT}:rate=${FPS}:duration=${DURATION}" \
    -frames:v "$FRAMES" -pix_fmt bgra \
    -f rawvideo \
    "$BGRA_FILE" 2>/dev/null
EXPECTED_SIZE=$((WIDTH * HEIGHT * 4 * FRAMES))
ACTUAL_SIZE=$(stat -c%s "$BGRA_FILE" 2>/dev/null || stat -f%z "$BGRA_FILE" 2>/dev/null)
if [[ "$ACTUAL_SIZE" -eq "$EXPECTED_SIZE" ]]; then
    log_pass "$BGRA_FILE ($ACTUAL_SIZE bytes, $FRAMES frames)"
else
    log_fail "Size mismatch: expected $EXPECTED_SIZE, got $ACTUAL_SIZE"
fi

# --- 3. H.264 reference bitstream (libx264 software encoder) ---
echo ""
echo "[3/4] H.264 reference bitstream (libx264)"
H264_FILE="$FIXTURE_DIR/testsrc2_${WIDTH}x${HEIGHT}.h264"
"$FFMPEG" -y -f rawvideo -pix_fmt nv12 -s "${WIDTH}x${HEIGHT}" -r "$FPS" \
    -i "$NV12_FILE" -frames:v "$FRAMES" \
    -c:v libx264 \
    -preset medium \
    -profile:v high \
    -x264opts "keyint=${FRAMES}:min-keyint=${FRAMES}:bframes=0:repeat-headers=1" \
    -pix_fmt yuv420p \
    -f h264 \
    "$H264_FILE" 2>/dev/null
H264_FRAMES=$("$FFMPEG" -i "$H264_FILE" -f null - 2>&1 | grep -oP 'frame=\s*\K\d+' | tail -1)
if [[ "$H264_FRAMES" -eq "$FRAMES" ]]; then
    log_pass "$H264_FILE ($H264_FRAMES frames, $(stat -c%s "$H264_FILE") bytes)"
else
    log_fail "Frame count mismatch: expected $FRAMES, got $H264_FRAMES"
fi

# --- 4. H.265 reference bitstream (libx265 software encoder) ---
echo ""
echo "[4/4] H.265 reference bitstream (libx265)"
H265_FILE="$FIXTURE_DIR/testsrc2_${WIDTH}x${HEIGHT}.h265"
"$FFMPEG" -y -f rawvideo -pix_fmt nv12 -s "${WIDTH}x${HEIGHT}" -r "$FPS" \
    -i "$NV12_FILE" -frames:v "$FRAMES" \
    -c:v libx265 \
    -preset medium \
    -profile:v main \
    -x265-params "keyint=${FRAMES}:min-keyint=${FRAMES}:bframes=0:repeat-headers=1" \
    -pix_fmt yuv420p \
    -f hevc \
    "$H265_FILE" 2>/dev/null
H265_FRAMES=$("$FFMPEG" -i "$H265_FILE" -f null - 2>&1 | grep -oP 'frame=\s*\K\d+' | tail -1)
if [[ "$H265_FRAMES" -eq "$FRAMES" ]]; then
    log_pass "$H265_FILE ($H265_FRAMES frames, $(stat -c%s "$H265_FILE") bytes)"
else
    log_fail "Frame count mismatch: expected $FRAMES, got $H265_FRAMES"
fi

# --- Summary ---
echo ""
echo "=== Fixture Summary ==="
echo "    Directory: $FIXTURE_DIR"
echo ""
echo "  Encoder inputs (raw frames):"
echo "    NV12: $(basename "$NV12_FILE") ($(du -h "$NV12_FILE" | cut -f1))"
echo "    BGRA: $(basename "$BGRA_FILE") ($(du -h "$BGRA_FILE" | cut -f1))"
echo ""
echo "  Decoder inputs (known-good, ffmpeg software encoded):"
echo "    H.264: $(basename "$H264_FILE") ($(du -h "$H264_FILE" | cut -f1))"
echo "    H.265: $(basename "$H265_FILE") ($(du -h "$H265_FILE" | cut -f1))"
echo ""
echo "=== Fixture generation complete ==="
