// Copyright (c) 2025 Jonathan Fontanez
// SPDX-License-Identifier: BUSL-1.1

#![allow(clippy::disallowed_macros)] // build.rs uses println!/eprintln! for `cargo:` directives

//! Build script: links Metal on Apple platforms; on Linux compiles the
//! Vulkan compute, vertex, fragment, and ray-tracing shaders this crate
//! ships (`vulkan/rhi/shaders/*.{comp,vert,frag,rgen,rmiss,rchit}`) to
//! SPIR-V via `glslc` and stages the artifacts in `OUT_DIR` for
//! `include_bytes!` to consume at compile time.

fn main() {
    // Link Metal framework on macOS for MP4 writer
    #[cfg(target_os = "macos")]
    {
        println!("cargo:rustc-link-lib=framework=Metal");
    }

    #[cfg(target_os = "linux")]
    compile_shaders();

    generate_embedded_schemas_table();
}

/// Read `streamlib.yaml`'s `schemas:` list and emit a generated Rust file
/// in `OUT_DIR/embedded_schemas_table.rs` containing a static table mapping
/// each schema's `metadata.name` to `include_str!()` of its YAML body.
///
/// The file is `include!`ed by `src/core/embedded_schemas.rs` (per #402),
/// replacing the hand-curated 21-arm match that historically drifted
/// against the on-disk schema set.
fn generate_embedded_schemas_table() {
    use std::path::PathBuf;

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let manifest_path = PathBuf::from(&manifest_dir).join("streamlib.yaml");
    println!("cargo:rerun-if-changed={}", manifest_path.display());

    let manifest_text = std::fs::read_to_string(&manifest_path).unwrap_or_else(|e| {
        panic!(
            "Failed to read {}: {} (#402 requires streamlib.yaml as the schemas source of truth)",
            manifest_path.display(),
            e
        )
    });

    let yaml: serde_yaml::Value = serde_yaml::from_str(&manifest_text)
        .expect("Failed to parse streamlib.yaml: invalid YAML");

    let schemas_list = yaml
        .get("schemas")
        .and_then(|v| v.as_sequence())
        .unwrap_or_else(|| {
            panic!(
                "streamlib.yaml must declare a `schemas:` array. Add the schema list before \
                 generating bindings (see #402 for the migration off [package.metadata.streamlib])"
            )
        });

    let mut entries: Vec<(String, String)> = Vec::with_capacity(schemas_list.len());
    for schema_value in schemas_list {
        let rel_path = schema_value
            .as_str()
            .expect("streamlib.yaml `schemas:` entries must be strings");
        let abs_path = PathBuf::from(&manifest_dir).join(rel_path);
        println!("cargo:rerun-if-changed={}", abs_path.display());

        let schema_text = std::fs::read_to_string(&abs_path).unwrap_or_else(|e| {
            panic!("Failed to read schema {}: {}", abs_path.display(), e)
        });
        let schema_yaml: serde_yaml::Value = serde_yaml::from_str(&schema_text)
            .unwrap_or_else(|e| panic!("Failed to parse schema {}: {}", abs_path.display(), e));

        let name = schema_yaml
            .get("metadata")
            .and_then(|m| m.get("name"))
            .and_then(|n| n.as_str())
            .unwrap_or_else(|| {
                panic!(
                    "schema {} missing `metadata.name` — required for embedded-schemas lookup",
                    abs_path.display()
                )
            });

        entries.push((name.to_string(), rel_path.to_string()));
    }

    // Sort by name for deterministic output.
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = PathBuf::from(out_dir).join("embedded_schemas_table.rs");

    let mut buf = String::new();
    buf.push_str("// AUTOGENERATED by build.rs from streamlib.yaml. DO NOT EDIT.\n\n");
    buf.push_str("/// Embedded schemas table — `(metadata.name, yaml_body)` pairs.\n");
    buf.push_str("///\n");
    buf.push_str(
        "/// Populated by `build.rs` from the `schemas:` list in `streamlib.yaml`.\n",
    );
    buf.push_str("/// Replaces the hand-curated 21-arm match that drifted against the\n");
    buf.push_str("/// on-disk schema set (resolved by #402).\n");
    buf.push_str("pub(crate) const EMBEDDED_SCHEMAS: &[(&str, &str)] = &[\n");
    for (name, rel) in &entries {
        buf.push_str(&format!(
            "    (\"{}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}\"))),\n",
            name, rel
        ));
    }
    buf.push_str("];\n");

    std::fs::write(&out_path, &buf).expect("Failed to write embedded_schemas_table.rs");
}

#[cfg(target_os = "linux")]
fn compile_shaders() {
    use std::path::{Path, PathBuf};
    use std::process::Command;

    // Per-stage shader sources. Each entry produces one SPIR-V module
    // consumed via `include_bytes!(concat!(env!("OUT_DIR"), …))`.
    // Add new kernels (compute, vertex, fragment) here.
    let shaders: &[(&str, &str, &str)] = &[
        ("src/vulkan/rhi/shaders/nv12_to_bgra.comp", "nv12_to_bgra.spv", "compute"),
        (
            "src/vulkan/rhi/shaders/display_blit.vert",
            "display_blit.vert.spv",
            "vertex",
        ),
        (
            "src/vulkan/rhi/shaders/display_blit.frag",
            "display_blit.frag.spv",
            "fragment",
        ),
    ];

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");

    for (src, dst, stage) in shaders {
        let src_path = Path::new(src);
        let dst_path: PathBuf = Path::new(&out_dir).join(dst);

        println!("cargo:rerun-if-changed={}", src);

        let status = Command::new("glslc")
            .arg(format!("-fshader-stage={stage}"))
            .arg("-O")
            .arg(src_path)
            .arg("-o")
            .arg(&dst_path)
            .status()
            .expect("Failed to run glslc. Install the Vulkan SDK or ensure glslc is in PATH.");

        assert!(status.success(), "glslc failed to compile {}", src);
    }

    // Parameterized test shaders: one .comp source compiled multiple times with
    // different `-DINPUT_COUNT=N` defines, producing one SPIR-V variant per
    // value. Used by parameterized descriptor-management tests.
    let test_blend_src = "src/vulkan/rhi/shaders/test_blend.comp";
    println!("cargo:rerun-if-changed={}", test_blend_src);
    for &n in &[1u32, 2, 4, 8] {
        let dst_path: PathBuf = Path::new(&out_dir).join(format!("test_blend_{n}.spv"));
        let status = Command::new("glslc")
            .arg("-fshader-stage=compute")
            .arg("-O")
            .arg(format!("-DINPUT_COUNT={n}"))
            .arg(Path::new(test_blend_src))
            .arg("-o")
            .arg(&dst_path)
            .status()
            .expect("Failed to run glslc for test_blend.comp");
        assert!(
            status.success(),
            "glslc failed to compile test_blend.comp with INPUT_COUNT={n}"
        );
    }

    // Ray-tracing shaders. Need Vulkan 1.2 + SPIR-V 1.4 minimum for the
    // `SPV_KHR_ray_tracing` opcodes; `glslc`'s default target is
    // Vulkan 1.0 / SPIR-V 1.0 which silently drops `GL_EXT_ray_tracing`.
    let rt_shaders: &[(&str, &str, &str)] = &[
        (
            "src/vulkan/rhi/shaders/raytracing_test.rgen",
            "raytracing_test.rgen.spv",
            "rgen",
        ),
        (
            "src/vulkan/rhi/shaders/raytracing_test.rmiss",
            "raytracing_test.rmiss.spv",
            "rmiss",
        ),
        (
            "src/vulkan/rhi/shaders/raytracing_test.rchit",
            "raytracing_test.rchit.spv",
            "rchit",
        ),
        (
            "src/vulkan/rhi/shaders/raytracing_showcase.rgen",
            "raytracing_showcase.rgen.spv",
            "rgen",
        ),
        (
            "src/vulkan/rhi/shaders/raytracing_showcase.rmiss",
            "raytracing_showcase.rmiss.spv",
            "rmiss",
        ),
        (
            "src/vulkan/rhi/shaders/raytracing_showcase.rchit",
            "raytracing_showcase.rchit.spv",
            "rchit",
        ),
    ];

    for (src, dst, stage) in rt_shaders {
        let src_path = Path::new(src);
        let dst_path: PathBuf = Path::new(&out_dir).join(dst);

        println!("cargo:rerun-if-changed={}", src);

        let status = Command::new("glslc")
            .arg(format!("-fshader-stage={stage}"))
            .arg("--target-env=vulkan1.2")
            .arg("--target-spv=spv1.4")
            .arg("-O")
            .arg(src_path)
            .arg("-o")
            .arg(&dst_path)
            .status()
            .expect("Failed to run glslc. Install the Vulkan SDK or ensure glslc is in PATH.");

        assert!(status.success(), "glslc failed to compile {}", src);
    }
}
