// Copyright (c) 2025 Jonathan Fontanez
// SPDX-License-Identifier: BUSL-1.1

#![allow(clippy::disallowed_macros)] // build.rs uses println!/eprintln! for `cargo:` directives

//! Build script: links Metal on Apple platforms; on Linux compiles the
//! Vulkan compute, vertex, fragment, and ray-tracing shaders this crate
//! ships (`vulkan/rhi/shaders/*.{comp,vert,frag,rgen,rmiss,rchit}`) to
//! SPIR-V via `glslc` and stages the artifacts in `OUT_DIR` for
//! `include_bytes!` to consume at compile time.

fn main() {
    // Link Metal framework on macOS for MP4 writer
    #[cfg(target_os = "macos")]
    {
        println!("cargo:rustc-link-lib=framework=Metal");
    }

    #[cfg(target_os = "linux")]
    compile_shaders();

    generate_embedded_schemas_table();
}

/// Walk `streamlib.yaml`'s `schemas:` list AND its `dependencies:` block
/// (per #401) to emit `EMBEDDED_SCHEMAS: &[(canonical_identifier, yaml_body)]`
/// in `OUT_DIR/embedded_schemas_table.rs`.
///
/// Canonical identifiers carry the unversioned form (no `@<semver>` suffix):
/// - Legacy schemas declaring `metadata.name` (reverse-DNS): the
///   `metadata.name` value verbatim.
/// - New-shape schemas declaring `metadata.type` inside a package-flavor
///   manifest: the joined `@<org>/<package>/<Type>`.
///
/// Sorted by canonical identifier for diff-stable output and binary-search
/// lookups. The file is `include!`ed by `src/core/embedded_schemas.rs`.
///
/// The previous build also emitted `EMBEDDED_SCHEMA_IDENT_SEGMENTS` (a
/// joined-versioned → structured-segments table for the wire boundary).
/// That table was deleted with #404 — the macro now emits structured
/// `PortDescriptor.schema: PortSchemaSpec` natively, so producers reach
/// `SchemaIdentWire::from_segments(...)` with structured fields directly,
/// without any joined-string→segments lookup.
fn generate_embedded_schemas_table() {
    use std::path::PathBuf;
    use streamlib_idents::resolve;

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let manifest_path = PathBuf::from(&manifest_dir).join("streamlib.yaml");
    println!("cargo:rerun-if-changed={}", manifest_path.display());

    let manifest_dir_path = PathBuf::from(&manifest_dir);
    let resolved = resolve(&manifest_dir_path).unwrap_or_else(|e| {
        panic!(
            "Failed to resolve streamlib.yaml dependency graph at {}: {}",
            manifest_dir_path.display(),
            e
        )
    });

    let mut name_entries: Vec<(String, String)> = Vec::new();

    for pkg in resolved.iter_all() {
        for schema_path in &pkg.schema_files {
            println!("cargo:rerun-if-changed={}", schema_path.display());

            let schema_text = std::fs::read_to_string(schema_path).unwrap_or_else(|e| {
                panic!("Failed to read schema {}: {}", schema_path.display(), e)
            });
            let schema_yaml: serde_yaml::Value =
                serde_yaml::from_str(&schema_text).unwrap_or_else(|e| {
                    panic!("Failed to parse schema {}: {}", schema_path.display(), e)
                });

            let canonical = resolve_canonical_identifier(&schema_yaml, pkg, schema_path);
            let include_path_literal = include_path_literal(&manifest_dir_path, schema_path);
            name_entries.push((canonical, include_path_literal));
        }
    }

    name_entries.sort_by(|a, b| a.0.cmp(&b.0));

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = PathBuf::from(out_dir).join("embedded_schemas_table.rs");

    let mut buf = String::new();
    buf.push_str("// AUTOGENERATED by build.rs from streamlib.yaml. DO NOT EDIT.\n\n");
    buf.push_str("/// Embedded schemas table — `(canonical_identifier, yaml_body)` pairs.\n");
    buf.push_str("///\n");
    buf.push_str(
        "/// Populated by `build.rs` walking `streamlib.yaml` + its dependency graph.\n",
    );
    buf.push_str(
        "/// Canonical identifiers carry the unversioned form (no @<semver> suffix); the\n",
    );
    buf.push_str(
        "/// runtime lookup helpers strip the version when callers pass it (#401).\n",
    );
    buf.push_str("pub(crate) const EMBEDDED_SCHEMAS: &[(&str, &str)] = &[\n");
    for (name, include_lit) in &name_entries {
        buf.push_str(&format!("    (\"{}\", {}),\n", name, include_lit));
    }
    buf.push_str("];\n");

    std::fs::write(&out_path, &buf).expect("Failed to write embedded_schemas_table.rs");
}

/// Resolve a schema's canonical (unversioned) lookup key from its parsed
/// YAML + the package context. New-shape schemas (declaring `metadata.type`
/// inside a package-flavor manifest) yield `@<org>/<package>/<Type>`; legacy
/// reverse-DNS schemas declaring `metadata.name` yield the name verbatim.
fn resolve_canonical_identifier(
    schema_yaml: &serde_yaml::Value,
    pkg: &streamlib_idents::ResolvedPackage,
    schema_path: &std::path::Path,
) -> String {
    let metadata = schema_yaml.get("metadata").unwrap_or_else(|| {
        panic!("schema {} missing `metadata` block", schema_path.display())
    });

    if let Some(type_name) = metadata.get("type").and_then(|t| t.as_str()) {
        let pkg_meta = pkg.manifest.package.as_ref().unwrap_or_else(|| {
            panic!(
                "schema {} declares metadata.type but its enclosing manifest is not a \
                 package-flavor streamlib.yaml (no `package:` block)",
                schema_path.display()
            )
        });
        return format!(
            "@{}/{}/{}",
            pkg_meta.org.as_str(),
            pkg_meta.name.as_str(),
            type_name
        );
    }

    if let Some(name) = metadata.get("name").and_then(|n| n.as_str()) {
        // Legacy reverse-DNS — strip any trailing @<semver> for canonical form.
        return strip_semver_suffix(name).to_string();
    }

    panic!(
        "schema {} must declare either `metadata.type` (new shape) or \
         `metadata.name` (legacy reverse-DNS) — required for embedded-schemas lookup",
        schema_path.display()
    )
}

/// Build the `include_str!(...)` literal for a schema body. Schemas owned
/// by the in-tree manifest go through `CARGO_MANIFEST_DIR` (relocatable);
/// schemas pulled in from path dependencies use the absolute resolved path
/// (the lockfile content-hash gate guarantees deterministic regen).
fn include_path_literal(
    manifest_dir: &std::path::Path,
    schema_path: &std::path::Path,
) -> String {
    if let Ok(rel) = schema_path.strip_prefix(manifest_dir) {
        format!(
            "include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}\"))",
            rel.to_string_lossy()
        )
    } else {
        format!("include_str!(\"{}\")", schema_path.to_string_lossy())
    }
}

/// Strip a trailing `@MAJOR.MINOR.PATCH` semver suffix. Returns the input
/// unchanged when there's no version suffix or when the trailing `@` opens
/// a non-semver string (the leading `@` of `@org/...` identifiers does not
/// open a version, so this strips the LAST `@` only when followed by
/// dotted digits).
fn strip_semver_suffix(name: &str) -> &str {
    if let Some(at_pos) = name.rfind('@') {
        let suffix = &name[at_pos + 1..];
        if is_semver(suffix) {
            return &name[..at_pos];
        }
    }
    name
}

fn is_semver(s: &str) -> bool {
    let parts: Vec<&str> = s.split('.').collect();
    if parts.len() != 3 {
        return false;
    }
    parts.iter().all(|p| !p.is_empty() && p.chars().all(|c| c.is_ascii_digit()))
}

#[cfg(target_os = "linux")]
fn compile_shaders() {
    use std::path::{Path, PathBuf};
    use std::process::Command;

    // Per-stage shader sources. Each entry produces one SPIR-V module
    // consumed via `include_bytes!(concat!(env!("OUT_DIR"), …))`.
    // Add new kernels (compute, vertex, fragment) here.
    let shaders: &[(&str, &str, &str)] = &[
        ("src/vulkan/rhi/shaders/nv12_to_bgra.comp", "nv12_to_bgra.spv", "compute"),
        (
            "src/vulkan/rhi/shaders/display_blit.vert",
            "display_blit.vert.spv",
            "vertex",
        ),
        (
            "src/vulkan/rhi/shaders/display_blit.frag",
            "display_blit.frag.spv",
            "fragment",
        ),
    ];

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");

    for (src, dst, stage) in shaders {
        let src_path = Path::new(src);
        let dst_path: PathBuf = Path::new(&out_dir).join(dst);

        println!("cargo:rerun-if-changed={}", src);

        let status = Command::new("glslc")
            .arg(format!("-fshader-stage={stage}"))
            .arg("-O")
            .arg(src_path)
            .arg("-o")
            .arg(&dst_path)
            .status()
            .expect("Failed to run glslc. Install the Vulkan SDK or ensure glslc is in PATH.");

        assert!(status.success(), "glslc failed to compile {}", src);
    }

    // Parameterized test shaders: one .comp source compiled multiple times with
    // different `-DINPUT_COUNT=N` defines, producing one SPIR-V variant per
    // value. Used by parameterized descriptor-management tests.
    let test_blend_src = "src/vulkan/rhi/shaders/test_blend.comp";
    println!("cargo:rerun-if-changed={}", test_blend_src);
    for &n in &[1u32, 2, 4, 8] {
        let dst_path: PathBuf = Path::new(&out_dir).join(format!("test_blend_{n}.spv"));
        let status = Command::new("glslc")
            .arg("-fshader-stage=compute")
            .arg("-O")
            .arg(format!("-DINPUT_COUNT={n}"))
            .arg(Path::new(test_blend_src))
            .arg("-o")
            .arg(&dst_path)
            .status()
            .expect("Failed to run glslc for test_blend.comp");
        assert!(
            status.success(),
            "glslc failed to compile test_blend.comp with INPUT_COUNT={n}"
        );
    }

    // Ray-tracing shaders. Need Vulkan 1.2 + SPIR-V 1.4 minimum for the
    // `SPV_KHR_ray_tracing` opcodes; `glslc`'s default target is
    // Vulkan 1.0 / SPIR-V 1.0 which silently drops `GL_EXT_ray_tracing`.
    let rt_shaders: &[(&str, &str, &str)] = &[
        (
            "src/vulkan/rhi/shaders/raytracing_test.rgen",
            "raytracing_test.rgen.spv",
            "rgen",
        ),
        (
            "src/vulkan/rhi/shaders/raytracing_test.rmiss",
            "raytracing_test.rmiss.spv",
            "rmiss",
        ),
        (
            "src/vulkan/rhi/shaders/raytracing_test.rchit",
            "raytracing_test.rchit.spv",
            "rchit",
        ),
        (
            "src/vulkan/rhi/shaders/raytracing_showcase.rgen",
            "raytracing_showcase.rgen.spv",
            "rgen",
        ),
        (
            "src/vulkan/rhi/shaders/raytracing_showcase.rmiss",
            "raytracing_showcase.rmiss.spv",
            "rmiss",
        ),
        (
            "src/vulkan/rhi/shaders/raytracing_showcase.rchit",
            "raytracing_showcase.rchit.spv",
            "rchit",
        ),
    ];

    for (src, dst, stage) in rt_shaders {
        let src_path = Path::new(src);
        let dst_path: PathBuf = Path::new(&out_dir).join(dst);

        println!("cargo:rerun-if-changed={}", src);

        let status = Command::new("glslc")
            .arg(format!("-fshader-stage={stage}"))
            .arg("--target-env=vulkan1.2")
            .arg("--target-spv=spv1.4")
            .arg("-O")
            .arg(src_path)
            .arg("-o")
            .arg(&dst_path)
            .status()
            .expect("Failed to run glslc. Install the Vulkan SDK or ensure glslc is in PATH.");

        assert!(status.success(), "glslc failed to compile {}", src);
    }
}
