#!/usr/bin/env bash
# Copyright (c) 2025 Jonathan Fontanez
# SPDX-License-Identifier: BUSL-1.1
#
# StreamLib Developer Setup
# Drops `cargo run` proxy scripts under .streamlib/bin so the CLI and runtime
# can be invoked by name from outside the workspace.
#
# Usage:
#   ./scripts/dev-setup.sh              # Setup local dev environment
#   ./scripts/dev-setup.sh uninstall    # Remove proxy scripts and .env
#   ./scripts/dev-setup.sh reinstall    # Uninstall then reinstall

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
STREAMLIB_HOME="${REPO_ROOT}/.streamlib"

PLATFORM="$(uname)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info() { echo -e "${BLUE}==>${NC} $1"; }
success() { echo -e "${GREEN}==>${NC} $1"; }
warn() { echo -e "${YELLOW}==>${NC} $1"; }
error() { echo -e "${RED}==>${NC} $1" >&2; }

check_platform() {
    case "$PLATFORM" in
        Darwin|Linux)
            info "Detected platform: $PLATFORM"
            ;;
        *)
            error "Unsupported platform: $PLATFORM (macOS and Linux only)"
            exit 1
            ;;
    esac
}

check_dependencies() {
    if ! command -v cargo &> /dev/null; then
        error "Rust/Cargo not found. Install from https://rustup.rs"
        exit 1
    fi
}

uninstall() {
    info "Uninstalling existing dev installation..."
    rm -rf "${STREAMLIB_HOME}"
    remove_dotenv
    success "Uninstalled"
}

generate_dotenv() {
    local env_file="${REPO_ROOT}/.env"
    info "Generating .env for dotenvy..."
    cat > "$env_file" << EOF
# StreamLib Development Environment
# Auto-generated by dev-setup.sh - re-run to regenerate

STREAMLIB_HOME=${STREAMLIB_HOME}
STREAMLIB_RUNTIME_BIN=${STREAMLIB_HOME}/bin/streamlib-runtime
STREAMLIB_DEV_MODE=1
EOF
    success "Generated .env (auto-loaded by runtime)"
}

remove_dotenv() {
    local env_file="${REPO_ROOT}/.env"
    if [[ -f "$env_file" ]]; then
        rm -f "$env_file"
        info "Removed .env"
    fi
}

create_proxy_scripts() {
    local bin_dir="${STREAMLIB_HOME}/bin"
    info "Creating proxy scripts..."
    mkdir -p "$bin_dir"

    local cargo_bin
    cargo_bin="$(dirname "$(which cargo)")"

    cat > "$bin_dir/streamlib" << EOF
#!/usr/bin/env bash
# StreamLib CLI proxy - calls cargo run for dev mode
set -euo pipefail
export PATH="${cargo_bin}:\$PATH"
export STREAMLIB_HOME="${STREAMLIB_HOME}"
export STREAMLIB_DEV_MODE=1
exec cargo run --manifest-path "${REPO_ROOT}/Cargo.toml" -p streamlib-cli --quiet -- "\$@"
EOF
    chmod 755 "$bin_dir/streamlib"
    success "Created CLI proxy: $bin_dir/streamlib"

    cat > "$bin_dir/streamlib-runtime" << EOF
#!/usr/bin/env bash
# StreamLib Runtime proxy - calls cargo run for dev mode
set -euo pipefail
export PATH="${cargo_bin}:\$PATH"
export STREAMLIB_HOME="${STREAMLIB_HOME}"
export STREAMLIB_DEV_MODE=1
exec cargo run --manifest-path "${REPO_ROOT}/Cargo.toml" -p streamlib-runtime --quiet -- "\$@"
EOF
    chmod 755 "$bin_dir/streamlib-runtime"
    success "Created runtime proxy: $bin_dir/streamlib-runtime"
}

install() {
    create_proxy_scripts
    generate_dotenv

    echo ""
    success "Dev setup complete!"
    echo ""
    echo "Proxy scripts installed under: ${STREAMLIB_HOME}/bin/"
    echo "Run 'direnv allow' to load environment variables, then:"
    echo "  ${STREAMLIB_HOME}/bin/streamlib --help"
    echo ""
}

main() {
    echo ""
    echo "StreamLib Developer Setup (Local Dev Mode)"
    echo "==========================================="
    echo ""

    check_platform
    check_dependencies

    local cmd="${1:-install}"
    case "$cmd" in
        uninstall)
            uninstall
            ;;
        reinstall|--clean)
            uninstall
            install
            ;;
        install|"")
            install
            ;;
        *)
            error "Unknown command: $cmd"
            echo ""
            echo "Usage:"
            echo "  ./scripts/dev-setup.sh              # Setup local dev environment"
            echo "  ./scripts/dev-setup.sh uninstall    # Remove proxy scripts and .env"
            echo "  ./scripts/dev-setup.sh reinstall    # Uninstall then reinstall"
            exit 1
            ;;
    esac
}

main "$@"
