// Copyright (c) 2025 Jonathan Fontanez
// SPDX-License-Identifier: BUSL-1.1
//
// Generated from JTD schema using jtd-codegen. DO NOT EDIT.

// Code generated by jtd-codegen for TypeScript v0.2.1

/**
 * Encoded audio frame with Opus/AAC bitstream data
 */
export interface EncodedAudioFrame {
  /**
   * Encoded audio bitstream data (Opus/AAC)
   */
  data: number[];

  /**
   * Number of audio samples per channel in this frame
   */
  sample_count: number;

  /**
   * Monotonic timestamp in nanoseconds (int64 as string)
   */
  timestamp_ns: string;
}
