// Copyright (c) 2025 Jonathan Fontanez
// SPDX-License-Identifier: BUSL-1.1

//! Renders `tatolab.stream`'s built-in node classes from the runtime's own
//! descriptors: one class per built-in, whose `type` is the path the runtime
//! registers it under, and one `TypedDict` per config, rendered from the
//! config's JSON Schema. The Rust declaration is the only one; `--check` is the
//! CI gate that fails when the checked-in module drifts from it.
//!
//! The descriptors come from `streamlib-media-builtins`' example
//! `print_built_in_node_descriptors`, so xtask itself links no engine.

use anyhow::{Context, Result, bail};
use serde_json::{Map, Value};
use std::fmt::Write as _;
use std::path::Path;

/// The generated module, relative to the workspace root.
pub const GENERATED_BUILT_IN_NODE_CLASSES_PATH: &str =
    "sdk/streamlib-python-wheel/python/tatolab/stream/_built_in_nodes.py";

/// What every built-in's `type` starts with; the rest is its class name.
const BUILT_IN_NODE_TYPE_PREFIX: &str = "tatolab.stream:";

/// The column a docstring line wraps before.
const DOCSTRING_WRAP_COLUMN: usize = 88;

const GENERATED_MODULE_HEADER: &str = r#"# Copyright (c) 2025 Jonathan Fontanez
# SPDX-License-Identifier: BUSL-1.1

# Generated by `cargo xtask generate-built-in-node-classes` from the runtime's
# built-in descriptors. Do not edit: CI fails when this file differs from a
# regeneration.

"""The runtime's built-in nodes, each with the shape of its config."""

from __future__ import annotations

from typing import ClassVar, Literal, TypedDict

from ._built_in_node import BuiltInNode
"#;

/// Regenerate the module, or with `check_only` fail when the checked-in one
/// differs from a regeneration.
pub fn run(workspace_root: &Path, check_only: bool) -> Result<()> {
    if !cfg!(target_os = "linux") {
        bail!(
            "generate-built-in-node-classes runs on Linux only: Linux is the floor that \
             compiles in every built-in, and a module rendered elsewhere would drop the ones \
             that floor lacks"
        );
    }
    let built_in_node_descriptors = built_in_node_descriptors_this_floor_registers(workspace_root)?;
    let rendered_module = render_built_in_node_classes_module(&built_in_node_descriptors)?;
    let generated_module_path = workspace_root.join(GENERATED_BUILT_IN_NODE_CLASSES_PATH);
    if check_only {
        let checked_in_module = std::fs::read_to_string(&generated_module_path)
            .with_context(|| format!("reading {}", generated_module_path.display()))?;
        if checked_in_module != rendered_module {
            bail!(
                "{GENERATED_BUILT_IN_NODE_CLASSES_PATH} differs from what the runtime's built-in \
                 descriptors render to. A built-in's declaration changed without the module being \
                 regenerated: run `cargo xtask generate-built-in-node-classes` and commit the result."
            );
        }
        tracing::info!("{GENERATED_BUILT_IN_NODE_CLASSES_PATH} matches the runtime's built-ins");
        return Ok(());
    }
    std::fs::write(&generated_module_path, rendered_module)
        .with_context(|| format!("writing {}", generated_module_path.display()))?;
    tracing::info!(
        "wrote {GENERATED_BUILT_IN_NODE_CLASSES_PATH} ({} built-ins)",
        built_in_node_descriptors.len()
    );
    Ok(())
}

fn built_in_node_descriptors_this_floor_registers(workspace_root: &Path) -> Result<Vec<Value>> {
    let output = std::process::Command::new("cargo")
        .current_dir(workspace_root)
        .args([
            "run",
            "--locked",
            "-q",
            "-p",
            "streamlib-media-builtins",
            "--example",
            "print_built_in_node_descriptors",
        ])
        .stderr(std::process::Stdio::inherit())
        .output()
        .context("running the print_built_in_node_descriptors example")?;
    if !output.status.success() {
        bail!(
            "the print_built_in_node_descriptors example exited with {}",
            output.status
        );
    }
    let descriptors: Value = serde_json::from_slice(&output.stdout)
        .context("parsing the built-in descriptors the example printed")?;
    match descriptors {
        Value::Array(descriptors) if !descriptors.is_empty() => Ok(descriptors),
        _ => bail!("the print_built_in_node_descriptors example printed no built-ins"),
    }
}

/// The generated module's text for `descriptors`, each a catalog entry as the
/// local API serves it.
pub fn render_built_in_node_classes_module(descriptors: &[Value]) -> Result<String> {
    let mut rendered_classes = Vec::with_capacity(descriptors.len());
    for descriptor in descriptors {
        rendered_classes.push(render_one_built_in_node(descriptor)?);
    }
    rendered_classes.sort_by(|left, right| left.class_name.cmp(&right.class_name));

    let mut exported_names: Vec<String> = rendered_classes
        .iter()
        .flat_map(|rendered| [rendered.class_name.clone(), rendered.config_name()])
        .collect();
    exported_names.sort();

    let mut module = String::from(GENERATED_MODULE_HEADER);
    module.push_str("\n__all__ = [\n");
    for exported_name in &exported_names {
        writeln!(module, "    \"{exported_name}\",")?;
    }
    module.push_str("]\n");
    for rendered in &rendered_classes {
        module.push_str(&rendered.text);
    }
    Ok(module)
}

struct RenderedBuiltInNode {
    class_name: String,
    text: String,
}

impl RenderedBuiltInNode {
    fn config_name(&self) -> String {
        config_name_of(&self.class_name)
    }
}

fn config_name_of(class_name: &str) -> String {
    format!("{class_name}Config")
}

fn render_one_built_in_node(descriptor: &Value) -> Result<RenderedBuiltInNode> {
    let built_in_node_type = string_field(descriptor, "type", "a built-in descriptor")?;
    let Some(class_name) = built_in_node_type.strip_prefix(BUILT_IN_NODE_TYPE_PREFIX) else {
        bail!("built-in `{built_in_node_type}` does not start with `{BUILT_IN_NODE_TYPE_PREFIX}`");
    };
    if class_name.is_empty() || !class_name.chars().all(|c| c.is_ascii_alphanumeric()) {
        bail!("built-in `{built_in_node_type}` does not name a Python class");
    }
    let what = format!("built-in `{class_name}`");
    let config_name = config_name_of(class_name);

    let mut text = String::new();
    text.push_str(&render_config_typed_dict(
        &config_name,
        class_name,
        descriptor.get("config_schema"),
        &what,
    )?);

    write!(
        text,
        "\n\nclass {class_name}(BuiltInNode[{config_name}]):\n"
    )?;
    let mut class_doc_paragraphs = vec![python_prose(
        &sentence(string_field(descriptor, "description", &what)?),
        &what,
    )?];
    for (heading, ports_key) in [("Inputs", "inputs"), ("Outputs", "outputs")] {
        let ports = descriptor
            .get(ports_key)
            .and_then(Value::as_array)
            .with_context(|| format!("{what} has no `{ports_key}` list"))?;
        if !ports.is_empty() {
            class_doc_paragraphs.push(render_port_paragraph(heading, ports, &what)?);
        }
    }
    class_doc_paragraphs.push(format!("Config: `{config_name}`."));
    text.push_str(&render_docstring(&class_doc_paragraphs, 4));
    writeln!(
        text,
        "\n    type: ClassVar[str] = {}",
        python_string_literal(built_in_node_type, &what)?
    )?;
    if class_name.starts_with("Test") {
        text.push_str(
            "\n    # Keeps pytest from collecting the `Test*`-named class in user suites.\n    \
             __test__: ClassVar[bool] = False\n",
        );
    }
    Ok(RenderedBuiltInNode {
        class_name: class_name.to_owned(),
        text,
    })
}

fn render_port_paragraph(heading: &str, ports: &[Value], what: &str) -> Result<String> {
    let mut paragraph = format!("{heading}:");
    for port in ports {
        let port_name = string_field(port, "name", what)?;
        let delivery_profile = match port.get("delivery_profile") {
            Some(Value::String(delivery_profile)) => format!(" ({delivery_profile})"),
            _ => String::new(),
        };
        let description = python_prose(&sentence(string_field(port, "description", what)?), what)?;
        write!(
            paragraph,
            "\n    `{port_name}`{delivery_profile}: {description}"
        )?;
    }
    Ok(paragraph)
}

fn render_config_typed_dict(
    config_name: &str,
    class_name: &str,
    config_schema: Option<&Value>,
    what: &str,
) -> Result<String> {
    let empty_properties = Map::new();
    let empty_definitions = Map::new();
    let (properties, required_keys, definitions) = match config_schema {
        None | Some(Value::Null) => (&empty_properties, Vec::new(), &empty_definitions),
        Some(config_schema) => {
            if config_schema.get("type").and_then(Value::as_str) != Some("object") {
                bail!("{what}'s config schema is not an object");
            }
            let required_keys: Vec<&str> = config_schema
                .get("required")
                .and_then(Value::as_array)
                .map(|required| required.iter().filter_map(Value::as_str).collect())
                .unwrap_or_default();
            (
                config_schema
                    .get("properties")
                    .and_then(Value::as_object)
                    .unwrap_or(&empty_properties),
                required_keys,
                config_schema
                    .get("$defs")
                    .and_then(Value::as_object)
                    .unwrap_or(&empty_definitions),
            )
        }
    };

    let mut required_fields = String::new();
    let mut optional_fields = String::new();
    for (key, property_schema) in properties {
        let field_what = format!("{what}'s config key `{key}`");
        let rendered_field = render_config_field(key, property_schema, definitions, &field_what)?;
        if required_keys.contains(&key.as_str()) {
            required_fields.push_str(&rendered_field);
        } else {
            optional_fields.push_str(&rendered_field);
        }
    }

    let config_doc = format!("`{class_name}`'s config: the keys `stream_builder.add` takes.");
    let mut text = String::new();
    if required_fields.is_empty() {
        write!(text, "\n\nclass {config_name}(TypedDict, total=False):\n")?;
    } else {
        // `Required` is 3.11+; a total base is how the 3.10 floor spells it.
        let required_keys_name = format!("_{config_name}RequiredKeys");
        write!(text, "\n\nclass {required_keys_name}(TypedDict):\n")?;
        text.push_str(&render_docstring(
            &[format!(
                "The keys `{class_name}`'s config cannot leave out."
            )],
            4,
        ));
        text.push_str(&required_fields);
        write!(
            text,
            "\n\nclass {config_name}({required_keys_name}, total=False):\n"
        )?;
    }
    text.push_str(&render_docstring(&[config_doc], 4));
    text.push_str(&optional_fields);
    Ok(text)
}

fn render_config_field(
    key: &str,
    property_schema: &Value,
    definitions: &Map<String, Value>,
    what: &str,
) -> Result<String> {
    if !key.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
        || key.starts_with(|c: char| c.is_ascii_digit())
    {
        bail!("{what} is not a Python identifier");
    }
    let python_type = python_type_of(property_schema, definitions, what)?;
    let mut paragraphs = Vec::new();
    if let Some(description) = property_schema.get("description").and_then(Value::as_str) {
        paragraphs.push(python_prose(description, what)?);
    }
    let enumerated_values = enumerated_string_values(property_schema, definitions, what)?;
    if enumerated_values
        .iter()
        .any(|(_, description)| description.is_some())
    {
        let mut values_paragraph = String::from("Values:");
        for (value, description) in &enumerated_values {
            write!(values_paragraph, "\n    `{value}`")?;
            if let Some(description) = description {
                write!(values_paragraph, ": {}", python_prose(description, what)?)?;
            }
        }
        paragraphs.push(values_paragraph);
    }
    match property_schema.get("default") {
        None | Some(Value::Null) => {}
        Some(default) => paragraphs.push(format!(
            "Default: `{}`.",
            python_scalar_literal(default, what)?
        )),
    }

    let mut text = format!("\n    {key}: {python_type}\n");
    if !paragraphs.is_empty() {
        text.push_str(&render_docstring(&paragraphs, 4));
    }
    Ok(text)
}

fn resolve_reference<'schema>(
    schema: &'schema Value,
    definitions: &'schema Map<String, Value>,
    what: &str,
) -> Result<&'schema Value> {
    let Some(reference) = schema.get("$ref").and_then(Value::as_str) else {
        return Ok(schema);
    };
    let Some(definition_name) = reference.strip_prefix("#/$defs/") else {
        bail!("{what} refers to `{reference}`, outside the schema's `$defs`");
    };
    definitions
        .get(definition_name)
        .with_context(|| format!("{what} refers to `{reference}`, which `$defs` lacks"))
}

fn single_all_of_member(schema: &Value, what: &str) -> Result<Option<Value>> {
    match schema.get("allOf") {
        None => Ok(None),
        Some(Value::Array(members)) if members.len() == 1 => Ok(Some(members[0].clone())),
        Some(_) => bail!("{what} has an `allOf` of more than one schema"),
    }
}

fn python_type_of(schema: &Value, definitions: &Map<String, Value>, what: &str) -> Result<String> {
    let schema = resolve_reference(schema, definitions, what)?;
    if let Some(member) = single_all_of_member(schema, what)? {
        return python_type_of(&member, definitions, what);
    }
    if let Some(Value::Array(members)) = schema.get("anyOf") {
        let mut alternatives = Vec::new();
        for member in members {
            push_unique(
                &mut alternatives,
                python_type_of(member, definitions, what)?,
            );
        }
        return Ok(union_of(alternatives));
    }
    let enumerated_values = enumerated_string_values(schema, definitions, what)?;
    if !enumerated_values.is_empty() {
        let literals: Vec<String> = enumerated_values
            .iter()
            .map(|(value, _)| python_string_literal(value, what))
            .collect::<Result<_>>()?;
        return Ok(format!("Literal[{}]", literals.join(", ")));
    }
    let json_types: Vec<&str> = match schema.get("type") {
        Some(Value::String(json_type)) => vec![json_type.as_str()],
        Some(Value::Array(json_types)) => json_types.iter().filter_map(Value::as_str).collect(),
        _ => bail!("{what} has a schema with no `type` this generator renders: {schema}"),
    };
    let mut alternatives = Vec::new();
    for json_type in json_types {
        let python_type = match json_type {
            "string" => "str",
            "integer" => "int",
            "number" => "float",
            "boolean" => "bool",
            "null" => "None",
            other => {
                bail!("{what} has the JSON type `{other}`, which this generator does not render")
            }
        };
        push_unique(&mut alternatives, python_type.to_owned());
    }
    Ok(union_of(alternatives))
}

/// The string values `schema` is limited to, each with its description, or none
/// when it is not a string enumeration.
fn enumerated_string_values(
    schema: &Value,
    definitions: &Map<String, Value>,
    what: &str,
) -> Result<Vec<(String, Option<String>)>> {
    let schema = resolve_reference(schema, definitions, what)?;
    if let Some(member) = single_all_of_member(schema, what)? {
        return enumerated_string_values(&member, definitions, what);
    }
    if let Some(Value::Array(members)) = schema.get("anyOf") {
        let mut values = Vec::new();
        for member in members {
            values.extend(enumerated_string_values(member, definitions, what)?);
        }
        return Ok(values);
    }
    if let Some(Value::Array(members)) = schema.get("oneOf") {
        let mut values = Vec::new();
        for member in members {
            let member_values = enumerated_string_values(member, definitions, what)?;
            if member_values.is_empty() {
                bail!("{what} has a `oneOf` member that is not a string value: {member}");
            }
            let member_description = member
                .get("description")
                .and_then(Value::as_str)
                .map(str::to_owned);
            values.extend(
                member_values.into_iter().map(|(value, description)| {
                    (value, description.or(member_description.clone()))
                }),
            );
        }
        return Ok(values);
    }
    match schema.get("enum") {
        None => Ok(Vec::new()),
        Some(Value::Array(values)) => values
            .iter()
            .map(|value| match value {
                Value::String(value) => Ok((value.clone(), None)),
                other => bail!("{what} enumerates the non-string value {other}"),
            })
            .collect(),
        Some(other) => bail!("{what} has an `enum` that is not a list: {other}"),
    }
}

fn push_unique(alternatives: &mut Vec<String>, alternative: String) {
    if !alternatives.contains(&alternative) {
        alternatives.push(alternative);
    }
}

/// `alternatives` joined into one union, `None` last.
fn union_of(mut alternatives: Vec<String>) -> String {
    if let Some(none_position) = alternatives
        .iter()
        .position(|alternative| alternative == "None")
    {
        let none = alternatives.remove(none_position);
        alternatives.push(none);
    }
    alternatives.join(" | ")
}

fn string_field<'descriptor>(
    descriptor: &'descriptor Value,
    key: &str,
    what: &str,
) -> Result<&'descriptor str> {
    descriptor
        .get(key)
        .and_then(Value::as_str)
        .with_context(|| format!("{what} has no string `{key}`"))
}

fn sentence(text: &str) -> String {
    let text = text.trim();
    if text.ends_with(['.', '!', '?']) {
        text.to_owned()
    } else {
        format!("{text}.")
    }
}

/// `rustdoc` as a Python author reads it: an intra-doc link becomes its
/// backticked name. A link through a path other than `Self::` names a Rust item
/// the author never sees, so it is refused rather than rendered.
fn python_prose(rustdoc: &str, what: &str) -> Result<String> {
    let mut prose = String::with_capacity(rustdoc.len());
    let mut rest = rustdoc;
    while let Some(link_start) = rest.find("[`") {
        prose.push_str(&rest[..link_start]);
        let after_link_start = &rest[link_start + 2..];
        let Some(link_end) = after_link_start.find("`]") else {
            bail!("{what}'s description opens an intra-doc link it never closes");
        };
        let linked = &after_link_start[..link_end];
        let linked = linked.strip_prefix("Self::").unwrap_or(linked);
        if linked.contains("::") {
            bail!(
                "{what}'s description links `{linked}`, a Rust path a Python author cannot \
                 follow; say what it means in the description instead"
            );
        }
        write!(prose, "`{linked}`")?;
        rest = &after_link_start[link_end + 2..];
    }
    prose.push_str(rest);
    if prose.contains("\"\"\"") {
        bail!("{what}'s description holds `\"\"\"`, which would end its docstring");
    }
    Ok(prose.replace('\\', "\\\\"))
}

fn python_string_literal(value: &str, what: &str) -> Result<String> {
    if value.contains(['"', '\\']) || value.chars().any(char::is_control) {
        bail!("{what} has the string {value:?}, which this generator does not quote");
    }
    Ok(format!("\"{value}\""))
}

fn python_scalar_literal(value: &Value, what: &str) -> Result<String> {
    match value {
        Value::Bool(true) => Ok("True".to_owned()),
        Value::Bool(false) => Ok("False".to_owned()),
        Value::Number(number) => Ok(number.to_string()),
        Value::String(string) => python_string_literal(string, what),
        other => bail!("{what} has the default {other}, which is not a scalar"),
    }
}

/// A docstring of `paragraphs` at `indent`, each wrapped to
/// [`DOCSTRING_WRAP_COLUMN`]. Within a paragraph a line indented past the
/// paragraph's first is a list item: it starts its own line, and its wrapped
/// lines hang under it.
fn render_docstring(paragraphs: &[String], indent: usize) -> String {
    let margin = " ".repeat(indent);
    let mut lines: Vec<String> = Vec::new();
    for (paragraph_index, paragraph) in paragraphs.iter().enumerate() {
        if paragraph_index > 0 {
            lines.push(String::new());
        }
        for (item_indent, text, starts_a_prose_paragraph) in paragraph_blocks(paragraph) {
            if starts_a_prose_paragraph {
                lines.push(String::new());
            }
            let first_prefix = " ".repeat(item_indent);
            let hanging_prefix = if item_indent > 0 {
                " ".repeat(item_indent + 4)
            } else {
                String::new()
            };
            let width = DOCSTRING_WRAP_COLUMN - indent;
            // The docstring's first line also carries its opening quotes.
            let first_line_width = if lines.is_empty() { width - 3 } else { width };
            lines.extend(wrap_words(
                &text,
                first_line_width,
                width,
                &first_prefix,
                &hanging_prefix,
            ));
        }
    }
    let mut docstring = String::new();
    if lines.len() == 1 && lines[0].len() + indent + 6 <= DOCSTRING_WRAP_COLUMN {
        let _ = writeln!(docstring, "{margin}\"\"\"{}\"\"\"", lines[0]);
        return docstring;
    }
    let _ = writeln!(docstring, "{margin}\"\"\"{}", lines[0]);
    for line in &lines[1..] {
        if line.is_empty() {
            docstring.push('\n');
        } else {
            let _ = writeln!(docstring, "{margin}{line}");
        }
    }
    let _ = writeln!(docstring, "{margin}\"\"\"");
    docstring
}

/// The blocks of one paragraph: `(indent, text, starts_a_prose_paragraph)`. A
/// blank line in the source separates prose paragraphs; an indented line is a
/// list item; any other line break is a soft wrap.
fn paragraph_blocks(paragraph: &str) -> Vec<(usize, String, bool)> {
    let mut blocks: Vec<(usize, String, bool)> = Vec::new();
    let mut starts_a_prose_paragraph = false;
    for source_line in paragraph.split('\n') {
        if source_line.trim().is_empty() {
            starts_a_prose_paragraph = true;
            continue;
        }
        let line_indent = source_line.len() - source_line.trim_start().len();
        let continues_the_previous_block = line_indent == 0
            && !starts_a_prose_paragraph
            && blocks.last().is_some_and(|(indent, _, _)| *indent == 0);
        if continues_the_previous_block {
            if let Some((_, text, _)) = blocks.last_mut() {
                text.push(' ');
                text.push_str(source_line.trim());
            }
            continue;
        }
        blocks.push((
            line_indent,
            source_line.trim().to_owned(),
            starts_a_prose_paragraph,
        ));
        starts_a_prose_paragraph = false;
    }
    blocks
}

fn wrap_words(
    text: &str,
    first_line_width: usize,
    width: usize,
    first_prefix: &str,
    hanging_prefix: &str,
) -> Vec<String> {
    let mut lines: Vec<String> = Vec::new();
    let mut line = String::from(first_prefix);
    let mut line_has_a_word = false;
    for word in text.split_whitespace() {
        let line_width = if lines.is_empty() {
            first_line_width
        } else {
            width
        };
        let fits = line.chars().count() + usize::from(line_has_a_word) + word.chars().count()
            <= line_width;
        if line_has_a_word && !fits {
            lines.push(std::mem::replace(&mut line, String::from(hanging_prefix)));
            line_has_a_word = false;
        }
        if line_has_a_word {
            line.push(' ');
        }
        line.push_str(word);
        line_has_a_word = true;
    }
    lines.push(line);
    lines
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    /// `DisplayWindow` as the runtime describes it: an input port with a
    /// delivery profile, defaults of three JSON types, and an enumeration
    /// reached through `$defs` — every shape a built-in config takes today.
    fn display_window_descriptor() -> Value {
        json!({
            "type": "tatolab.stream:DisplayWindow",
            "description": "Shows video frames in a window with vsync",
            "repository": "https://github.com/tatolab/streamlib",
            "runtime": "rust",
            "config_schema": {
                "title": "DisplayWindowConfig",
                "description": "Configuration for [`DisplayWindow`].",
                "type": "object",
                "properties": {
                    "height": {
                        "description": "Initial window height, in the desktop's logical pixels.",
                        "default": 720, "type": "integer", "format": "uint32", "minimum": 0.0
                    },
                    "scaling": {
                        "description": "How the frame maps onto the window.",
                        "default": "fit",
                        "allOf": [{"$ref": "#/$defs/DisplayScaling"}]
                    },
                    "title": {"description": "Window title.", "default": "StreamLib", "type": "string"},
                    "device_id": {
                        "description": "Paired with [`Self::height`].",
                        "default": null, "type": ["string", "null"]
                    }
                },
                "additionalProperties": false,
                "$defs": {
                    "DisplayScaling": {
                        "oneOf": [
                            {"description": "Whole frame visible.", "type": "string", "enum": ["fit"]},
                            {"description": "Window covered.", "type": "string", "enum": ["fill"]}
                        ]
                    }
                }
            },
            "inputs": [{
                "name": "video", "description": "Video frames to show in the window",
                "required": true, "delivery_profile": "newest"
            }],
            "outputs": [],
            "examples": {"rust": "", "python": "", "typescript": ""}
        })
    }

    #[test]
    fn one_built_in_renders_to_its_golden_class_and_config() {
        let rendered = render_built_in_node_classes_module(&[display_window_descriptor()]).unwrap();
        let golden = format!(
            "{GENERATED_MODULE_HEADER}{}",
            r#"
__all__ = [
    "DisplayWindow",
    "DisplayWindowConfig",
]


class DisplayWindowConfig(TypedDict, total=False):
    """`DisplayWindow`'s config: the keys `stream_builder.add` takes."""

    height: int
    """Initial window height, in the desktop's logical pixels.

    Default: `720`.
    """

    scaling: Literal["fit", "fill"]
    """How the frame maps onto the window.

    Values:
        `fit`: Whole frame visible.
        `fill`: Window covered.

    Default: `"fit"`.
    """

    title: str
    """Window title.

    Default: `"StreamLib"`.
    """

    device_id: str | None
    """Paired with `height`."""


class DisplayWindow(BuiltInNode[DisplayWindowConfig]):
    """Shows video frames in a window with vsync.

    Inputs:
        `video` (newest): Video frames to show in the window.

    Config: `DisplayWindowConfig`.
    """

    type: ClassVar[str] = "tatolab.stream:DisplayWindow"
"#
        );
        assert_eq!(rendered, golden, "rendered:\n{rendered}");
    }

    #[test]
    fn a_required_key_renders_in_a_total_base_and_a_test_named_class_opts_out_of_pytest() {
        let descriptor = json!({
            "type": "tatolab.stream:TestRecorder",
            "description": "Records",
            "config_schema": {
                "type": "object",
                "required": ["path"],
                "properties": {"path": {"description": "The file.", "type": "string"}}
            },
            "inputs": [],
            "outputs": [{"name": "done", "description": "Done", "required": true, "delivery_profile": null}]
        });
        let rendered = render_built_in_node_classes_module(&[descriptor]).unwrap();
        assert!(
            rendered.contains(
                "class _TestRecorderConfigRequiredKeys(TypedDict):\n    \"\"\"The keys \
                 `TestRecorder`'s config cannot leave out.\"\"\"\n\n    path: str\n"
            ),
            "{rendered}"
        );
        assert!(
            rendered.contains(
                "class TestRecorderConfig(_TestRecorderConfigRequiredKeys, total=False):"
            ),
            "{rendered}"
        );
        assert!(rendered.contains("        `done`: Done.\n"), "{rendered}");
        assert!(
            rendered.contains("    __test__: ClassVar[bool] = False\n"),
            "{rendered}"
        );
    }

    #[test]
    fn a_description_linking_a_rust_path_is_refused_by_name() {
        let mut descriptor = display_window_descriptor();
        descriptor["config_schema"]["properties"]["title"]["description"] =
            json!("Absent means [`DisplayScaling::Fit`].");
        let refusal = render_built_in_node_classes_module(&[descriptor])
            .unwrap_err()
            .to_string();
        assert!(refusal.contains("`DisplayScaling::Fit`"), "{refusal}");
        assert!(refusal.contains("config key `title`"), "{refusal}");
    }

    #[test]
    fn a_json_type_the_generator_does_not_render_is_refused_by_name() {
        let mut descriptor = display_window_descriptor();
        descriptor["config_schema"]["properties"]["title"] = json!({"type": "array"});
        let refusal = render_built_in_node_classes_module(&[descriptor])
            .unwrap_err()
            .to_string();
        assert!(refusal.contains("`array`"), "{refusal}");
        assert!(
            refusal.contains("`DisplayWindow`'s config key `title`"),
            "{refusal}"
        );
    }

    #[test]
    fn a_type_outside_the_stream_package_is_refused() {
        let mut descriptor = display_window_descriptor();
        descriptor["type"] = json!("streamlib_media_builtins::DisplayWindow");
        let refusal = render_built_in_node_classes_module(&[descriptor])
            .unwrap_err()
            .to_string();
        assert!(refusal.contains("tatolab.stream:"), "{refusal}");
    }

    #[test]
    fn a_long_description_wraps_before_the_column_and_list_items_hang() {
        let docstring = render_docstring(
            &[
                "word ".repeat(40),
                format!("Values:\n    `fit`: {}", "item ".repeat(30)),
            ],
            4,
        );
        for line in docstring.lines() {
            assert!(line.chars().count() <= DOCSTRING_WRAP_COLUMN, "{line:?}");
        }
        assert!(docstring.contains("\n        `fit`: item"), "{docstring}");
        assert!(docstring.contains("\n            item"), "{docstring}");
    }
}
