// Copyright (c) 2025 Jonathan Fontanez
// SPDX-License-Identifier: BUSL-1.1

//! Schema registry, looked up by canonical identifier.
//!
//! Two population paths feed the same registry:
//!
//! 1. **Engine compile-time const** (`EMBEDDED_SCHEMAS`, generated by
//!    `build.rs` walking `streamlib.yaml`'s `schemas:` list AND its
//!    resolved `dependencies:` graph per #401). Seeds the registry on
//!    first lookup.
//! 2. **Runtime registration** via [`register_schema`], invoked by
//!    `Runner::load_project` for every `schemas:` entry in a loaded
//!    package's `streamlib.yaml` (#729). This is how domain crates
//!    (`@tatolab/audio`, future carve-outs) reach the introspection
//!    paths without the engine declaring them as deps.
//!
//! Canonical identifiers are stored unversioned:
//! - Legacy reverse-DNS: `com.streamlib.h264_encoder.config`
//! - New structured: `@tatolab/core/VideoFrame`
//!
//! Lookups tolerate either the unversioned form or the versioned suffix
//! `@MAJOR.MINOR.PATCH`; the version is stripped before comparing.

use parking_lot::RwLock;
use std::collections::HashMap;
use std::sync::{Arc, LazyLock};

#[cfg(test)]
mod integration_tests;

include!(concat!(env!("OUT_DIR"), "/embedded_schemas_table.rs"));

/// Runtime-mutable schema registry. Seeded lazily from
/// [`EMBEDDED_SCHEMAS`] on first access; mutable thereafter via
/// [`register_schema`] (called from `Runner::load_project` for each
/// loaded package's `schemas:` entries).
static SCHEMA_REGISTRY: LazyLock<RwLock<HashMap<String, Arc<str>>>> = LazyLock::new(|| {
    let mut map = HashMap::with_capacity(EMBEDDED_SCHEMAS.len());
    for (canonical, body) in EMBEDDED_SCHEMAS {
        map.insert((*canonical).to_string(), Arc::from(*body));
    }
    RwLock::new(map)
});

/// Register a schema's YAML body under its canonical identifier. Last
/// write wins. Idempotent for identical bodies; the engine's compile-
/// time entries are seeded into the registry on first lookup, so
/// runtime registrations from `Runner::load_project` overwrite the
/// const-seeded entry only if a domain crate's `streamlib.yaml`
/// declares the same canonical id (which would be an error the caller
/// surfaces — but the registry doesn't enforce uniqueness).
pub fn register_schema(canonical_id: impl Into<String>, body: impl Into<Arc<str>>) {
    let canonical = canonical_id.into();
    let body = body.into();
    let mut guard = SCHEMA_REGISTRY.write();
    guard.insert(canonical, body);
}

/// Get the schema's YAML body for a canonical identifier.
///
/// Accepts both unversioned (`@tatolab/core/VideoFrame`) and versioned
/// (`@tatolab/core/VideoFrame@1.0.0`) forms; the version suffix is
/// stripped before lookup.
pub fn get_embedded_schema_definition(name: &str) -> Option<Arc<str>> {
    let canonical = strip_semver_suffix(name);
    SCHEMA_REGISTRY.read().get(canonical).cloned()
}

/// Extract `max_payload_bytes` from a schema's metadata section.
///
/// Tolerates both unversioned and versioned forms. Returns the iceoryx2
/// default when the schema is unknown or doesn't declare a payload bound.
pub fn max_payload_bytes_for_schema(schema_name: &str) -> usize {
    use crate::iceoryx2::MAX_PAYLOAD_SIZE;
    if let Some(yaml) = get_embedded_schema_definition(schema_name) {
        if let Ok(value) = serde_yaml::from_str::<serde_yaml::Value>(&yaml) {
            if let Some(n) = value
                .get("metadata")
                .and_then(|m| m.get("max_payload_bytes"))
                .and_then(|v| v.as_u64())
            {
                return n as usize;
            }
        }
    }
    MAX_PAYLOAD_SIZE as usize
}

/// Resolve `max_payload_bytes` from a structured port-schema spec by
/// rendering it to its canonical lookup form via `Display`. Returns the
/// iceoryx2 default for `Any` and for unknown schemas.
pub fn max_payload_bytes_for_port_spec(
    schema_spec: &streamlib_processor_schema::PortSchemaSpec,
) -> usize {
    max_payload_bytes_for_schema(&schema_spec.to_string())
}

/// List every registered schema's canonical identifier (unversioned).
/// Sorted alphabetically so consumers (api-server) get diff-stable
/// output across processes and across the const/runtime split.
pub fn list_embedded_schema_names() -> Vec<String> {
    let mut names: Vec<String> = SCHEMA_REGISTRY.read().keys().cloned().collect();
    names.sort();
    names
}

/// Strip a trailing `@MAJOR.MINOR.PATCH` suffix from an identifier. The
/// leading `@` of `@org/...` identifiers is *not* stripped — this only
/// fires when the last `@` is followed by a dotted-digits semver.
///
/// Examples:
/// - `@tatolab/core/VideoFrame@1.0.0` → `@tatolab/core/VideoFrame`
/// - `@tatolab/core/VideoFrame` → unchanged
/// - `com.streamlib.h264_encoder.config@1.0.0` → `com.streamlib.h264_encoder.config`
/// - `com.streamlib.h264_encoder.config` → unchanged
pub(crate) fn strip_semver_suffix(name: &str) -> &str {
    if let Some(at_pos) = name.rfind('@') {
        let suffix = &name[at_pos + 1..];
        if is_semver(suffix) {
            return &name[..at_pos];
        }
    }
    name
}

fn is_semver(s: &str) -> bool {
    let parts: Vec<&str> = s.split('.').collect();
    if parts.len() != 3 {
        return false;
    }
    parts.iter().all(|p| !p.is_empty() && p.chars().all(|c| c.is_ascii_digit()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_table_is_populated() {
        assert!(
            !EMBEDDED_SCHEMAS.is_empty(),
            "build.rs must populate the embedded schema table from streamlib.yaml"
        );
    }

    #[test]
    fn lookup_finds_wire_vocabulary_via_new_identifier() {
        let yaml = get_embedded_schema_definition("@tatolab/core/VideoFrame");
        assert!(
            yaml.is_some(),
            "wire vocabulary VideoFrame must be embedded under the new identifier"
        );
        assert!(
            yaml.unwrap().contains("metadata"),
            "embedded schema body should contain its metadata block"
        );
    }

    #[test]
    fn lookup_strips_version_suffix() {
        // Both unversioned and versioned forms must hit the same entry.
        let unversioned = get_embedded_schema_definition("@tatolab/core/AudioFrame");
        let versioned = get_embedded_schema_definition("@tatolab/core/AudioFrame@1.0.0");
        assert!(unversioned.is_some());
        assert_eq!(unversioned.as_deref(), versioned.as_deref());
    }

    #[test]
    fn lookup_strips_legacy_version_suffix() {
        // Legacy reverse-DNS form still works.
        let unversioned = get_embedded_schema_definition("com.streamlib.h264_encoder.config");
        let versioned =
            get_embedded_schema_definition("com.streamlib.h264_encoder.config@1.0.0");
        assert!(unversioned.is_some());
        assert_eq!(unversioned.as_deref(), versioned.as_deref());
    }

    #[test]
    fn lookup_returns_none_for_unknown_schema() {
        assert!(get_embedded_schema_definition("does.not.exist").is_none());
        assert!(get_embedded_schema_definition("@nonexistent/pkg/Type").is_none());
    }

    #[test]
    fn list_is_sorted() {
        let names = list_embedded_schema_names();
        let mut sorted = names.clone();
        sorted.sort();
        assert_eq!(names, sorted, "list_embedded_schema_names must return sorted output");
    }

    #[test]
    fn no_duplicate_names() {
        let names = list_embedded_schema_names();
        let unique: std::collections::HashSet<&String> = names.iter().collect();
        assert_eq!(
            names.len(),
            unique.len(),
            "duplicate canonical identifier across schemas — fix streamlib.yaml or its deps"
        );
    }

    #[test]
    fn max_payload_bytes_returns_default_for_unknown() {
        use crate::iceoryx2::MAX_PAYLOAD_SIZE;
        assert_eq!(
            max_payload_bytes_for_schema("does.not.exist"),
            MAX_PAYLOAD_SIZE as usize
        );
    }

    #[test]
    fn max_payload_bytes_resolves_video_frame_via_either_form() {
        // VideoFrame's schema declares max_payload_bytes: 65536. The
        // helper must return 65536 from both unversioned and versioned
        // forms (the bug class #401 fixed: leading `@` in the new
        // grammar broke `split('@').next()` parser).
        let unv = max_payload_bytes_for_schema("@tatolab/core/VideoFrame");
        let v = max_payload_bytes_for_schema("@tatolab/core/VideoFrame@1.0.0");
        assert_eq!(unv, v);
        assert!(unv >= 65536, "VideoFrame should declare a generous payload bound");
    }

    #[test]
    fn strip_semver_suffix_handles_new_grammar() {
        assert_eq!(
            strip_semver_suffix("@tatolab/core/VideoFrame@1.0.0"),
            "@tatolab/core/VideoFrame"
        );
        // The leading `@` of `@org/...` identifiers is NOT a version marker.
        assert_eq!(
            strip_semver_suffix("@tatolab/core/VideoFrame"),
            "@tatolab/core/VideoFrame"
        );
    }

    #[test]
    fn strip_semver_suffix_handles_legacy_grammar() {
        assert_eq!(
            strip_semver_suffix("com.tatolab.foo@1.0.0"),
            "com.tatolab.foo"
        );
        assert_eq!(strip_semver_suffix("com.tatolab.foo"), "com.tatolab.foo");
    }

    #[test]
    fn register_schema_inserts_runtime_entry() {
        // Use a unique key not in EMBEDDED_SCHEMAS so the test is
        // independent of build-time state.
        let canonical = "@tatolab/test_register_inserts/RuntimeOnlyType";
        let body = "metadata:\n  type: RuntimeOnlyType\n  max_payload_bytes: 4096\n";

        // Pre-condition: not present.
        assert!(get_embedded_schema_definition(canonical).is_none());

        register_schema(canonical, body);

        // Post-condition: lookup finds it.
        let got = get_embedded_schema_definition(canonical).expect("registered schema must resolve");
        assert!(got.contains("RuntimeOnlyType"));

        // max_payload_bytes_for_schema reads the metadata.
        assert_eq!(max_payload_bytes_for_schema(canonical), 4096);

        // List includes it (sorted).
        assert!(list_embedded_schema_names().iter().any(|n| n == canonical));
    }

    #[test]
    fn register_schema_overwrite_is_last_write_wins() {
        let canonical = "@tatolab/test_register_overwrite/RewrittenType";
        register_schema(canonical, "metadata:\n  type: RewrittenType\n  max_payload_bytes: 1024\n");
        assert_eq!(max_payload_bytes_for_schema(canonical), 1024);
        register_schema(canonical, "metadata:\n  type: RewrittenType\n  max_payload_bytes: 2048\n");
        assert_eq!(max_payload_bytes_for_schema(canonical), 2048);
    }

    #[test]
    fn register_schema_versioned_lookup_strips_to_canonical() {
        let canonical = "@tatolab/test_register_versioned/StripsVersion";
        register_schema(canonical, "metadata:\n  type: StripsVersion\n");
        // Versioned lookup hits the same entry.
        assert!(get_embedded_schema_definition(&format!("{canonical}@1.0.0")).is_some());
    }
}
