// This file is @generated by prost-build.
/// Health check
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetHealthRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetHealthResponse {
    #[prost(bool, tag = "1")]
    pub healthy: bool,
    /// "ok", "degraded", etc.
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub uptime_secs: i64,
}
/// Version info
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetVersionRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetVersionResponse {
    /// e.g., "0.2.4"
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    /// Short commit hash if available
    #[prost(string, tag = "2")]
    pub git_commit: ::prost::alloc::string::String,
    /// ISO 8601 date
    #[prost(string, tag = "3")]
    pub build_date: ::prost::alloc::string::String,
    /// Bump when gRPC API changes (for compatibility check)
    #[prost(uint32, tag = "4")]
    pub protocol_version: u32,
}
/// Runtime listing
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListRuntimesRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RuntimeInfo {
    #[prost(string, tag = "1")]
    pub runtime_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub registered_at_unix_ms: i64,
    #[prost(int32, tag = "3")]
    pub processor_count: i32,
    #[prost(int32, tag = "4")]
    pub connection_count: i32,
    /// Human-readable runtime name
    #[prost(string, tag = "5")]
    pub name: ::prost::alloc::string::String,
    /// API server endpoint (e.g., "127.0.0.1:9000")
    #[prost(string, tag = "6")]
    pub api_endpoint: ::prost::alloc::string::String,
    /// Path to runtime log file
    #[prost(string, tag = "7")]
    pub log_path: ::prost::alloc::string::String,
    /// Process ID of the runtime
    #[prost(int32, tag = "8")]
    pub pid: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListRuntimesResponse {
    #[prost(message, repeated, tag = "1")]
    pub runtimes: ::prost::alloc::vec::Vec<RuntimeInfo>,
}
/// Processor listing
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProcessorsRequest {
    /// Empty = all runtimes
    #[prost(string, tag = "1")]
    pub runtime_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProcessorInfo {
    #[prost(string, tag = "1")]
    pub runtime_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub processor_id: ::prost::alloc::string::String,
    /// e.g., "PythonContinuousProcessor"
    #[prost(string, tag = "3")]
    pub processor_type: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub registered_at_unix_ms: i64,
    /// "connected", "awaiting", "failed"
    #[prost(string, tag = "5")]
    pub bridge_state: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProcessorsResponse {
    #[prost(message, repeated, tag = "1")]
    pub processors: ::prost::alloc::vec::Vec<ProcessorInfo>,
}
/// Connection listing
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListConnectionsRequest {
    /// Empty = all runtimes
    #[prost(string, tag = "1")]
    pub runtime_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConnectionInfo {
    #[prost(string, tag = "1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub runtime_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub processor_id: ::prost::alloc::string::String,
    /// "runtime" or "subprocess"
    #[prost(string, tag = "4")]
    pub role: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub established_at_unix_ms: i64,
    #[prost(int64, tag = "6")]
    pub frames_transferred: i64,
    #[prost(int64, tag = "7")]
    pub bytes_transferred: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListConnectionsResponse {
    #[prost(message, repeated, tag = "1")]
    pub connections: ::prost::alloc::vec::Vec<ConnectionInfo>,
}
/// Runtime endpoint lookup (DNS-like)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRuntimeEndpointRequest {
    /// Query can be by name or ID
    #[prost(oneof = "get_runtime_endpoint_request::Query", tags = "1, 2")]
    pub query: ::core::option::Option<get_runtime_endpoint_request::Query>,
}
/// Nested message and enum types in `GetRuntimeEndpointRequest`.
pub mod get_runtime_endpoint_request {
    /// Query can be by name or ID
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Query {
        /// Look up by human-readable name
        #[prost(string, tag = "1")]
        Name(::prost::alloc::string::String),
        /// Look up by runtime ID
        #[prost(string, tag = "2")]
        RuntimeId(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRuntimeEndpointResponse {
    #[prost(bool, tag = "1")]
    pub found: bool,
    #[prost(string, tag = "2")]
    pub runtime_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    /// e.g., "127.0.0.1:9000"
    #[prost(string, tag = "4")]
    pub api_endpoint: ::prost::alloc::string::String,
    /// e.g., "/Users/x/.streamlib/logs/fancy-tiger.log"
    #[prost(string, tag = "5")]
    pub log_path: ::prost::alloc::string::String,
}
/// Runtime registration (called by runtime on startup via gRPC)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterRuntimeRequest {
    /// Unique runtime ID
    #[prost(string, tag = "1")]
    pub runtime_id: ::prost::alloc::string::String,
    /// Human-readable name (e.g., "fancy-tiger")
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// API server endpoint (e.g., "127.0.0.1:9000")
    #[prost(string, tag = "3")]
    pub api_endpoint: ::prost::alloc::string::String,
    /// Path to log file
    #[prost(string, tag = "4")]
    pub log_path: ::prost::alloc::string::String,
    /// Process ID of the runtime
    #[prost(int32, tag = "5")]
    pub pid: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterRuntimeResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// Error message if success is false
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// Runtime unregistration (called by runtime on shutdown)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnregisterRuntimeRequest {
    #[prost(string, tag = "1")]
    pub runtime_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UnregisterRuntimeResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
/// Prune dead runtimes
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PruneDeadRuntimesRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PruneDeadRuntimesResponse {
    /// Number of runtimes removed
    #[prost(int32, tag = "1")]
    pub pruned_count: i32,
    /// Names of removed runtimes
    #[prost(string, repeated, tag = "2")]
    pub pruned_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// AllocateConnection - Host processor allocates a connection before spawning subprocess
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AllocateConnectionRequest {
    #[prost(string, tag = "1")]
    pub runtime_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub processor_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AllocateConnectionResponse {
    /// Pass to subprocess via env var
    #[prost(string, tag = "1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub success: bool,
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
/// HostAlive - Host reports alive (Rust code is running)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HostAliveRequest {
    #[prost(string, tag = "1")]
    pub connection_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HostAliveResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// "pending", "alive", "xpc_ready", etc.
    #[prost(string, tag = "2")]
    pub client_state: ::prost::alloc::string::String,
}
/// HostXpcReady - Host confirms XPC endpoint was stored (called AFTER XPC store_endpoint)
/// NOTE: The actual endpoint is transferred via XPC, not gRPC (Mach ports can't serialize)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HostXpcReadyRequest {
    /// NO xpc_endpoint field - endpoint already stored via XPC message
    #[prost(string, tag = "1")]
    pub connection_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HostXpcReadyResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub client_state: ::prost::alloc::string::String,
}
/// ClientAlive - Subprocess reports alive (first contact with broker)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientAliveRequest {
    /// From env var STREAMLIB_CONNECTION_ID
    #[prost(string, tag = "1")]
    pub connection_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientAliveResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// "pending", "alive", "xpc_ready", etc.
    #[prost(string, tag = "2")]
    pub host_state: ::prost::alloc::string::String,
}
/// GetClientStatus - Host polls for client status
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetClientStatusRequest {
    #[prost(string, tag = "1")]
    pub connection_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetClientStatusResponse {
    /// "pending", "alive", "xpc_ready", "acked", "failed"
    #[prost(string, tag = "1")]
    pub client_state: ::prost::alloc::string::String,
}
/// GetHostStatus - Client polls for host status
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetHostStatusRequest {
    #[prost(string, tag = "1")]
    pub connection_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetHostStatusResponse {
    /// NOTE: No xpc_endpoint field - XPC endpoints transferred via broker XPC interface, not gRPC
    #[prost(string, tag = "1")]
    pub host_state: ::prost::alloc::string::String,
}
/// MarkAcked - Either side marks their ACK complete
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarkAckedRequest {
    #[prost(string, tag = "1")]
    pub connection_id: ::prost::alloc::string::String,
    /// "host" or "client"
    #[prost(string, tag = "2")]
    pub side: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarkAckedResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// "awaiting_ack", "ready"
    #[prost(string, tag = "2")]
    pub connection_state: ::prost::alloc::string::String,
}
/// GetConnectionInfo - Get full connection info (for debugging)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConnectionInfoRequest {
    #[prost(string, tag = "1")]
    pub connection_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConnectionInfoResponse {
    #[prost(bool, tag = "1")]
    pub found: bool,
    #[prost(string, tag = "2")]
    pub host_state: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub client_state: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub derived_state: ::prost::alloc::string::String,
    /// Whether host has stored endpoint
    #[prost(bool, tag = "5")]
    pub host_xpc_endpoint_stored: bool,
    /// Whether client has connected to host
    #[prost(bool, tag = "6")]
    pub client_connected: bool,
    #[prost(int64, tag = "7")]
    pub age_secs: i64,
    #[prost(int64, tag = "8")]
    pub timeout_secs: i64,
}
/// CloseConnection - Called by host processor on teardown to release broker resources
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CloseConnectionRequest {
    #[prost(string, tag = "1")]
    pub connection_id: ::prost::alloc::string::String,
    /// "shutdown", "error", "timeout", etc.
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CloseConnectionResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
/// Generated client implementations.
pub mod broker_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// BrokerService provides diagnostics and monitoring for the XPC broker.
    /// Used by CLI tools to inspect broker state without affecting frame transfer.
    #[derive(Debug, Clone)]
    pub struct BrokerServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl BrokerServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> BrokerServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> BrokerServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            BrokerServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Health check - verify broker is responsive
        pub async fn get_health(
            &mut self,
            request: impl tonic::IntoRequest<super::GetHealthRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetHealthResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/streamlib.broker.BrokerService/GetHealth",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("streamlib.broker.BrokerService", "GetHealth"));
            self.inner.unary(req, path, codec).await
        }
        /// Version info - get broker version and build info
        pub async fn get_version(
            &mut self,
            request: impl tonic::IntoRequest<super::GetVersionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetVersionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/streamlib.broker.BrokerService/GetVersion",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("streamlib.broker.BrokerService", "GetVersion"));
            self.inner.unary(req, path, codec).await
        }
        /// List all registered runtimes
        pub async fn list_runtimes(
            &mut self,
            request: impl tonic::IntoRequest<super::ListRuntimesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListRuntimesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/streamlib.broker.BrokerService/ListRuntimes",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("streamlib.broker.BrokerService", "ListRuntimes"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// List processors for a specific runtime
        pub async fn list_processors(
            &mut self,
            request: impl tonic::IntoRequest<super::ListProcessorsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListProcessorsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/streamlib.broker.BrokerService/ListProcessors",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("streamlib.broker.BrokerService", "ListProcessors"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// List active XPC connections
        pub async fn list_connections(
            &mut self,
            request: impl tonic::IntoRequest<super::ListConnectionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListConnectionsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/streamlib.broker.BrokerService/ListConnections",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("streamlib.broker.BrokerService", "ListConnections"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get runtime endpoint by name or ID (DNS-like lookup)
        pub async fn get_runtime_endpoint(
            &mut self,
            request: impl tonic::IntoRequest<super::GetRuntimeEndpointRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetRuntimeEndpointResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/streamlib.broker.BrokerService/GetRuntimeEndpoint",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "streamlib.broker.BrokerService",
                        "GetRuntimeEndpoint",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Register a runtime (called by runtime on startup)
        pub async fn register_runtime(
            &mut self,
            request: impl tonic::IntoRequest<super::RegisterRuntimeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterRuntimeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/streamlib.broker.BrokerService/RegisterRuntime",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("streamlib.broker.BrokerService", "RegisterRuntime"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Unregister a runtime (called by runtime on shutdown)
        pub async fn unregister_runtime(
            &mut self,
            request: impl tonic::IntoRequest<super::UnregisterRuntimeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UnregisterRuntimeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/streamlib.broker.BrokerService/UnregisterRuntime",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "streamlib.broker.BrokerService",
                        "UnregisterRuntime",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Prune dead runtimes (removes runtimes whose PIDs no longer exist)
        pub async fn prune_dead_runtimes(
            &mut self,
            request: impl tonic::IntoRequest<super::PruneDeadRuntimesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PruneDeadRuntimesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/streamlib.broker.BrokerService/PruneDeadRuntimes",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "streamlib.broker.BrokerService",
                        "PruneDeadRuntimes",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Host processor allocates a connection before spawning subprocess
        pub async fn allocate_connection(
            &mut self,
            request: impl tonic::IntoRequest<super::AllocateConnectionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AllocateConnectionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/streamlib.broker.BrokerService/AllocateConnection",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "streamlib.broker.BrokerService",
                        "AllocateConnection",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Host reports alive (Rust code is running)
        pub async fn host_alive(
            &mut self,
            request: impl tonic::IntoRequest<super::HostAliveRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HostAliveResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/streamlib.broker.BrokerService/HostAlive",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("streamlib.broker.BrokerService", "HostAlive"));
            self.inner.unary(req, path, codec).await
        }
        /// Host confirms XPC endpoint was stored (called AFTER XPC store_endpoint)
        /// NOTE: The actual endpoint is transferred via XPC, not gRPC (Mach ports can't serialize)
        pub async fn host_xpc_ready(
            &mut self,
            request: impl tonic::IntoRequest<super::HostXpcReadyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HostXpcReadyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/streamlib.broker.BrokerService/HostXpcReady",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("streamlib.broker.BrokerService", "HostXpcReady"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Subprocess reports alive (first contact with broker)
        pub async fn client_alive(
            &mut self,
            request: impl tonic::IntoRequest<super::ClientAliveRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ClientAliveResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/streamlib.broker.BrokerService/ClientAlive",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("streamlib.broker.BrokerService", "ClientAlive"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Host polls for client status
        pub async fn get_client_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetClientStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetClientStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/streamlib.broker.BrokerService/GetClientStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("streamlib.broker.BrokerService", "GetClientStatus"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Client polls for host status
        pub async fn get_host_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetHostStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetHostStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/streamlib.broker.BrokerService/GetHostStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("streamlib.broker.BrokerService", "GetHostStatus"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Either side marks their ACK complete
        pub async fn mark_acked(
            &mut self,
            request: impl tonic::IntoRequest<super::MarkAckedRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MarkAckedResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/streamlib.broker.BrokerService/MarkAcked",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("streamlib.broker.BrokerService", "MarkAcked"));
            self.inner.unary(req, path, codec).await
        }
        /// Get full connection info (for debugging)
        pub async fn get_connection_info(
            &mut self,
            request: impl tonic::IntoRequest<super::GetConnectionInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetConnectionInfoResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/streamlib.broker.BrokerService/GetConnectionInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "streamlib.broker.BrokerService",
                        "GetConnectionInfo",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Called by host processor on teardown to release broker resources
        pub async fn close_connection(
            &mut self,
            request: impl tonic::IntoRequest<super::CloseConnectionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CloseConnectionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/streamlib.broker.BrokerService/CloseConnection",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("streamlib.broker.BrokerService", "CloseConnection"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod broker_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with BrokerServiceServer.
    #[async_trait]
    pub trait BrokerService: std::marker::Send + std::marker::Sync + 'static {
        /// Health check - verify broker is responsive
        async fn get_health(
            &self,
            request: tonic::Request<super::GetHealthRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetHealthResponse>,
            tonic::Status,
        >;
        /// Version info - get broker version and build info
        async fn get_version(
            &self,
            request: tonic::Request<super::GetVersionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetVersionResponse>,
            tonic::Status,
        >;
        /// List all registered runtimes
        async fn list_runtimes(
            &self,
            request: tonic::Request<super::ListRuntimesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListRuntimesResponse>,
            tonic::Status,
        >;
        /// List processors for a specific runtime
        async fn list_processors(
            &self,
            request: tonic::Request<super::ListProcessorsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListProcessorsResponse>,
            tonic::Status,
        >;
        /// List active XPC connections
        async fn list_connections(
            &self,
            request: tonic::Request<super::ListConnectionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListConnectionsResponse>,
            tonic::Status,
        >;
        /// Get runtime endpoint by name or ID (DNS-like lookup)
        async fn get_runtime_endpoint(
            &self,
            request: tonic::Request<super::GetRuntimeEndpointRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetRuntimeEndpointResponse>,
            tonic::Status,
        >;
        /// Register a runtime (called by runtime on startup)
        async fn register_runtime(
            &self,
            request: tonic::Request<super::RegisterRuntimeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterRuntimeResponse>,
            tonic::Status,
        >;
        /// Unregister a runtime (called by runtime on shutdown)
        async fn unregister_runtime(
            &self,
            request: tonic::Request<super::UnregisterRuntimeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UnregisterRuntimeResponse>,
            tonic::Status,
        >;
        /// Prune dead runtimes (removes runtimes whose PIDs no longer exist)
        async fn prune_dead_runtimes(
            &self,
            request: tonic::Request<super::PruneDeadRuntimesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PruneDeadRuntimesResponse>,
            tonic::Status,
        >;
        /// Host processor allocates a connection before spawning subprocess
        async fn allocate_connection(
            &self,
            request: tonic::Request<super::AllocateConnectionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AllocateConnectionResponse>,
            tonic::Status,
        >;
        /// Host reports alive (Rust code is running)
        async fn host_alive(
            &self,
            request: tonic::Request<super::HostAliveRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HostAliveResponse>,
            tonic::Status,
        >;
        /// Host confirms XPC endpoint was stored (called AFTER XPC store_endpoint)
        /// NOTE: The actual endpoint is transferred via XPC, not gRPC (Mach ports can't serialize)
        async fn host_xpc_ready(
            &self,
            request: tonic::Request<super::HostXpcReadyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HostXpcReadyResponse>,
            tonic::Status,
        >;
        /// Subprocess reports alive (first contact with broker)
        async fn client_alive(
            &self,
            request: tonic::Request<super::ClientAliveRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ClientAliveResponse>,
            tonic::Status,
        >;
        /// Host polls for client status
        async fn get_client_status(
            &self,
            request: tonic::Request<super::GetClientStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetClientStatusResponse>,
            tonic::Status,
        >;
        /// Client polls for host status
        async fn get_host_status(
            &self,
            request: tonic::Request<super::GetHostStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetHostStatusResponse>,
            tonic::Status,
        >;
        /// Either side marks their ACK complete
        async fn mark_acked(
            &self,
            request: tonic::Request<super::MarkAckedRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MarkAckedResponse>,
            tonic::Status,
        >;
        /// Get full connection info (for debugging)
        async fn get_connection_info(
            &self,
            request: tonic::Request<super::GetConnectionInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetConnectionInfoResponse>,
            tonic::Status,
        >;
        /// Called by host processor on teardown to release broker resources
        async fn close_connection(
            &self,
            request: tonic::Request<super::CloseConnectionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CloseConnectionResponse>,
            tonic::Status,
        >;
    }
    /// BrokerService provides diagnostics and monitoring for the XPC broker.
    /// Used by CLI tools to inspect broker state without affecting frame transfer.
    #[derive(Debug)]
    pub struct BrokerServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> BrokerServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for BrokerServiceServer<T>
    where
        T: BrokerService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/streamlib.broker.BrokerService/GetHealth" => {
                    #[allow(non_camel_case_types)]
                    struct GetHealthSvc<T: BrokerService>(pub Arc<T>);
                    impl<
                        T: BrokerService,
                    > tonic::server::UnaryService<super::GetHealthRequest>
                    for GetHealthSvc<T> {
                        type Response = super::GetHealthResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetHealthRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrokerService>::get_health(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetHealthSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/streamlib.broker.BrokerService/GetVersion" => {
                    #[allow(non_camel_case_types)]
                    struct GetVersionSvc<T: BrokerService>(pub Arc<T>);
                    impl<
                        T: BrokerService,
                    > tonic::server::UnaryService<super::GetVersionRequest>
                    for GetVersionSvc<T> {
                        type Response = super::GetVersionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetVersionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrokerService>::get_version(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetVersionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/streamlib.broker.BrokerService/ListRuntimes" => {
                    #[allow(non_camel_case_types)]
                    struct ListRuntimesSvc<T: BrokerService>(pub Arc<T>);
                    impl<
                        T: BrokerService,
                    > tonic::server::UnaryService<super::ListRuntimesRequest>
                    for ListRuntimesSvc<T> {
                        type Response = super::ListRuntimesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListRuntimesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrokerService>::list_runtimes(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListRuntimesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/streamlib.broker.BrokerService/ListProcessors" => {
                    #[allow(non_camel_case_types)]
                    struct ListProcessorsSvc<T: BrokerService>(pub Arc<T>);
                    impl<
                        T: BrokerService,
                    > tonic::server::UnaryService<super::ListProcessorsRequest>
                    for ListProcessorsSvc<T> {
                        type Response = super::ListProcessorsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListProcessorsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrokerService>::list_processors(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListProcessorsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/streamlib.broker.BrokerService/ListConnections" => {
                    #[allow(non_camel_case_types)]
                    struct ListConnectionsSvc<T: BrokerService>(pub Arc<T>);
                    impl<
                        T: BrokerService,
                    > tonic::server::UnaryService<super::ListConnectionsRequest>
                    for ListConnectionsSvc<T> {
                        type Response = super::ListConnectionsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListConnectionsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrokerService>::list_connections(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListConnectionsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/streamlib.broker.BrokerService/GetRuntimeEndpoint" => {
                    #[allow(non_camel_case_types)]
                    struct GetRuntimeEndpointSvc<T: BrokerService>(pub Arc<T>);
                    impl<
                        T: BrokerService,
                    > tonic::server::UnaryService<super::GetRuntimeEndpointRequest>
                    for GetRuntimeEndpointSvc<T> {
                        type Response = super::GetRuntimeEndpointResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetRuntimeEndpointRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrokerService>::get_runtime_endpoint(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetRuntimeEndpointSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/streamlib.broker.BrokerService/RegisterRuntime" => {
                    #[allow(non_camel_case_types)]
                    struct RegisterRuntimeSvc<T: BrokerService>(pub Arc<T>);
                    impl<
                        T: BrokerService,
                    > tonic::server::UnaryService<super::RegisterRuntimeRequest>
                    for RegisterRuntimeSvc<T> {
                        type Response = super::RegisterRuntimeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RegisterRuntimeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrokerService>::register_runtime(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RegisterRuntimeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/streamlib.broker.BrokerService/UnregisterRuntime" => {
                    #[allow(non_camel_case_types)]
                    struct UnregisterRuntimeSvc<T: BrokerService>(pub Arc<T>);
                    impl<
                        T: BrokerService,
                    > tonic::server::UnaryService<super::UnregisterRuntimeRequest>
                    for UnregisterRuntimeSvc<T> {
                        type Response = super::UnregisterRuntimeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UnregisterRuntimeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrokerService>::unregister_runtime(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UnregisterRuntimeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/streamlib.broker.BrokerService/PruneDeadRuntimes" => {
                    #[allow(non_camel_case_types)]
                    struct PruneDeadRuntimesSvc<T: BrokerService>(pub Arc<T>);
                    impl<
                        T: BrokerService,
                    > tonic::server::UnaryService<super::PruneDeadRuntimesRequest>
                    for PruneDeadRuntimesSvc<T> {
                        type Response = super::PruneDeadRuntimesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PruneDeadRuntimesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrokerService>::prune_dead_runtimes(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PruneDeadRuntimesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/streamlib.broker.BrokerService/AllocateConnection" => {
                    #[allow(non_camel_case_types)]
                    struct AllocateConnectionSvc<T: BrokerService>(pub Arc<T>);
                    impl<
                        T: BrokerService,
                    > tonic::server::UnaryService<super::AllocateConnectionRequest>
                    for AllocateConnectionSvc<T> {
                        type Response = super::AllocateConnectionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AllocateConnectionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrokerService>::allocate_connection(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AllocateConnectionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/streamlib.broker.BrokerService/HostAlive" => {
                    #[allow(non_camel_case_types)]
                    struct HostAliveSvc<T: BrokerService>(pub Arc<T>);
                    impl<
                        T: BrokerService,
                    > tonic::server::UnaryService<super::HostAliveRequest>
                    for HostAliveSvc<T> {
                        type Response = super::HostAliveResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HostAliveRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrokerService>::host_alive(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HostAliveSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/streamlib.broker.BrokerService/HostXpcReady" => {
                    #[allow(non_camel_case_types)]
                    struct HostXpcReadySvc<T: BrokerService>(pub Arc<T>);
                    impl<
                        T: BrokerService,
                    > tonic::server::UnaryService<super::HostXpcReadyRequest>
                    for HostXpcReadySvc<T> {
                        type Response = super::HostXpcReadyResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HostXpcReadyRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrokerService>::host_xpc_ready(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HostXpcReadySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/streamlib.broker.BrokerService/ClientAlive" => {
                    #[allow(non_camel_case_types)]
                    struct ClientAliveSvc<T: BrokerService>(pub Arc<T>);
                    impl<
                        T: BrokerService,
                    > tonic::server::UnaryService<super::ClientAliveRequest>
                    for ClientAliveSvc<T> {
                        type Response = super::ClientAliveResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ClientAliveRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrokerService>::client_alive(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ClientAliveSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/streamlib.broker.BrokerService/GetClientStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetClientStatusSvc<T: BrokerService>(pub Arc<T>);
                    impl<
                        T: BrokerService,
                    > tonic::server::UnaryService<super::GetClientStatusRequest>
                    for GetClientStatusSvc<T> {
                        type Response = super::GetClientStatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetClientStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrokerService>::get_client_status(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetClientStatusSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/streamlib.broker.BrokerService/GetHostStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetHostStatusSvc<T: BrokerService>(pub Arc<T>);
                    impl<
                        T: BrokerService,
                    > tonic::server::UnaryService<super::GetHostStatusRequest>
                    for GetHostStatusSvc<T> {
                        type Response = super::GetHostStatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetHostStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrokerService>::get_host_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetHostStatusSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/streamlib.broker.BrokerService/MarkAcked" => {
                    #[allow(non_camel_case_types)]
                    struct MarkAckedSvc<T: BrokerService>(pub Arc<T>);
                    impl<
                        T: BrokerService,
                    > tonic::server::UnaryService<super::MarkAckedRequest>
                    for MarkAckedSvc<T> {
                        type Response = super::MarkAckedResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MarkAckedRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrokerService>::mark_acked(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MarkAckedSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/streamlib.broker.BrokerService/GetConnectionInfo" => {
                    #[allow(non_camel_case_types)]
                    struct GetConnectionInfoSvc<T: BrokerService>(pub Arc<T>);
                    impl<
                        T: BrokerService,
                    > tonic::server::UnaryService<super::GetConnectionInfoRequest>
                    for GetConnectionInfoSvc<T> {
                        type Response = super::GetConnectionInfoResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetConnectionInfoRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrokerService>::get_connection_info(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetConnectionInfoSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/streamlib.broker.BrokerService/CloseConnection" => {
                    #[allow(non_camel_case_types)]
                    struct CloseConnectionSvc<T: BrokerService>(pub Arc<T>);
                    impl<
                        T: BrokerService,
                    > tonic::server::UnaryService<super::CloseConnectionRequest>
                    for CloseConnectionSvc<T> {
                        type Response = super::CloseConnectionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CloseConnectionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BrokerService>::close_connection(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CloseConnectionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for BrokerServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "streamlib.broker.BrokerService";
    impl<T> tonic::server::NamedService for BrokerServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
