# Copyright (c) 2025 Jonathan Fontanez
# SPDX-License-Identifier: BUSL-1.1
#
# Generated from JTD schema using jtd-codegen. DO NOT EDIT.

# Code generated by jtd-codegen for Python v0.3.1

import re
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, Optional, Union, get_args, get_origin


@dataclass
class EffectConfig:
    """
    Configuration for CLAP audio plugin processing
    """

    buffer_size: 'int'
    """
    Processing buffer size in samples
    """

    plugin_path: 'str'
    """
    Path to the CLAP plugin file
    """

    plugin_index: 'Optional[int]'
    """
    Index of the plugin to load (if multiple in file)
    """

    plugin_name: 'Optional[str]'
    """
    Name of the plugin to load (if multiple in file)
    """


    @classmethod
    def from_json_data(cls, data: Any) -> 'EffectConfig':
        return cls(
            _from_json_data(int, data.get("buffer_size")),
            _from_json_data(str, data.get("plugin_path")),
            _from_json_data(Optional[int], data.get("plugin_index")),
            _from_json_data(Optional[str], data.get("plugin_name")),
        )

    def to_json_data(self) -> Any:
        data: Dict[str, Any] = {}
        data["buffer_size"] = _to_json_data(self.buffer_size)
        data["plugin_path"] = _to_json_data(self.plugin_path)
        if self.plugin_index is not None:
             data["plugin_index"] = _to_json_data(self.plugin_index)
        if self.plugin_name is not None:
             data["plugin_name"] = _to_json_data(self.plugin_name)
        return data

def _from_json_data(cls: Any, data: Any) -> Any:
    if data is None or cls in [bool, int, float, str, object] or cls is Any:
        return data
    if cls is datetime:
        return _parse_rfc3339(data)
    if get_origin(cls) is Union:
        return _from_json_data(get_args(cls)[0], data)
    if get_origin(cls) is list:
        return [_from_json_data(get_args(cls)[0], d) for d in data]
    if get_origin(cls) is dict:
        return { k: _from_json_data(get_args(cls)[1], v) for k, v in data.items() }
    return cls.from_json_data(data)

def _to_json_data(data: Any) -> Any:
    if data is None or type(data) in [bool, int, float, str, object]:
        return data
    if type(data) is datetime:
        return data.isoformat()
    if type(data) is list:
        return [_to_json_data(d) for d in data]
    if type(data) is dict:
        return { k: _to_json_data(v) for k, v in data.items() }
    return data.to_json_data()

def _parse_rfc3339(s: str) -> datetime:
    datetime_re = '^(\d{4})-(\d{2})-(\d{2})[tT](\d{2}):(\d{2}):(\d{2})(\.\d+)?([zZ]|((\+|-)(\d{2}):(\d{2})))$'
    match = re.match(datetime_re, s)
    if not match:
        raise ValueError('Invalid RFC3339 date/time', s)

    (year, month, day, hour, minute, second, frac_seconds, offset,
     *tz) = match.groups()

    frac_seconds_parsed = None
    if frac_seconds:
        frac_seconds_parsed = int(float(frac_seconds) * 1_000_000)
    else:
        frac_seconds_parsed = 0

    tzinfo = None
    if offset == 'Z':
        tzinfo = timezone.utc
    else:
        hours = int(tz[2])
        minutes = int(tz[3])
        sign = 1 if tz[1] == '+' else -1

        if minutes not in range(60):
            raise ValueError('minute offset must be in 0..59')

        tzinfo = timezone(timedelta(minutes=sign * (60 * hours + minutes)))

    second_parsed = int(second)
    if second_parsed == 60:
        second_parsed = 59

    return datetime(int(year), int(month), int(day), int(hour), int(minute),
                    second_parsed, frac_seconds_parsed, tzinfo)            
