# Copyright (c) 2025 Jonathan Fontanez
# SPDX-License-Identifier: BUSL-1.1
#
# Generated from JTD schema using jtd-codegen. DO NOT EDIT.

# Code generated by jtd-codegen for Python v0.3.1

import re
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, Optional, Union, get_args, get_origin


@dataclass
class BgraFileSourceConfig:
    """
    Configuration for streaming raw BGRA frames from a file.
    """

    file_path: 'str'
    """
    Path to raw BGRA file (width * height * 4 bytes per frame).
    """

    fps: 'int'
    """
    Playback frame rate.
    """

    frame_count: 'int'
    """
    Number of frames in the file.
    """

    height: 'int'
    """
    Frame height in pixels.
    """

    width: 'int'
    """
    Frame width in pixels.
    """


    @classmethod
    def from_json_data(cls, data: Any) -> 'BgraFileSourceConfig':
        return cls(
            _from_json_data(str, data.get("file_path")),
            _from_json_data(int, data.get("fps")),
            _from_json_data(int, data.get("frame_count")),
            _from_json_data(int, data.get("height")),
            _from_json_data(int, data.get("width")),
        )

    def to_json_data(self) -> Any:
        data: Dict[str, Any] = {}
        data["file_path"] = _to_json_data(self.file_path)
        data["fps"] = _to_json_data(self.fps)
        data["frame_count"] = _to_json_data(self.frame_count)
        data["height"] = _to_json_data(self.height)
        data["width"] = _to_json_data(self.width)
        return data

def _from_json_data(cls: Any, data: Any) -> Any:
    if data is None or cls in [bool, int, float, str, object] or cls is Any:
        return data
    if cls is datetime:
        return _parse_rfc3339(data)
    if get_origin(cls) is Union:
        return _from_json_data(get_args(cls)[0], data)
    if get_origin(cls) is list:
        return [_from_json_data(get_args(cls)[0], d) for d in data]
    if get_origin(cls) is dict:
        return { k: _from_json_data(get_args(cls)[1], v) for k, v in data.items() }
    return cls.from_json_data(data)

def _to_json_data(data: Any) -> Any:
    if data is None or type(data) in [bool, int, float, str, object]:
        return data
    if type(data) is datetime:
        return data.isoformat()
    if type(data) is list:
        return [_to_json_data(d) for d in data]
    if type(data) is dict:
        return { k: _to_json_data(v) for k, v in data.items() }
    return data.to_json_data()

def _parse_rfc3339(s: str) -> datetime:
    datetime_re = '^(\d{4})-(\d{2})-(\d{2})[tT](\d{2}):(\d{2}):(\d{2})(\.\d+)?([zZ]|((\+|-)(\d{2}):(\d{2})))$'
    match = re.match(datetime_re, s)
    if not match:
        raise ValueError('Invalid RFC3339 date/time', s)

    (year, month, day, hour, minute, second, frac_seconds, offset,
     *tz) = match.groups()

    frac_seconds_parsed = None
    if frac_seconds:
        frac_seconds_parsed = int(float(frac_seconds) * 1_000_000)
    else:
        frac_seconds_parsed = 0

    tzinfo = None
    if offset == 'Z':
        tzinfo = timezone.utc
    else:
        hours = int(tz[2])
        minutes = int(tz[3])
        sign = 1 if tz[1] == '+' else -1

        if minutes not in range(60):
            raise ValueError('minute offset must be in 0..59')

        tzinfo = timezone(timedelta(minutes=sign * (60 * hours + minutes)))

    second_parsed = int(second)
    if second_parsed == 60:
        second_parsed = 59

    return datetime(int(year), int(month), int(day), int(hour), int(minute),
                    second_parsed, frac_seconds_parsed, tzinfo)            
