# Copyright (c) 2025 Jonathan Fontanez
# SPDX-License-Identifier: BUSL-1.1
#
# Generated from JTD schema using jtd-codegen. DO NOT EDIT.

# Code generated by jtd-codegen for Python v0.3.1

import re
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import Any, Dict, List, Optional, Type, Union, get_args, get_origin


@dataclass
class EscalateRequest:
    """
    Polyglot subprocess escalate-on-behalf request (subprocess → host)
    """

    op: 'str'

    @classmethod
    def from_json_data(cls, data: Any) -> 'EscalateRequest':
        variants: Dict[str, Type[EscalateRequest]] = {
            "acquire_pixel_buffer": EscalateRequestAcquirePixelBuffer,
            "acquire_texture": EscalateRequestAcquireTexture,
            "log": EscalateRequestLog,
            "release_handle": EscalateRequestReleaseHandle,
        }

        return variants[data["op"]].from_json_data(data)

    def to_json_data(self) -> Any:
        pass

@dataclass
class EscalateRequestAcquirePixelBuffer(EscalateRequest):
    format: 'str'
    """
    Pixel format identifier (e.g. bgra32, nv12_video_range, gray8).
    """

    height: 'int'
    """
    Pixel height of the buffer.
    """

    request_id: 'str'
    """
    Correlates request with response. UUID string.
    """

    width: 'int'
    """
    Pixel width of the buffer.
    """


    @classmethod
    def from_json_data(cls, data: Any) -> 'EscalateRequestAcquirePixelBuffer':
        return cls(
            "acquire_pixel_buffer",
            _from_json_data(str, data.get("format")),
            _from_json_data(int, data.get("height")),
            _from_json_data(str, data.get("request_id")),
            _from_json_data(int, data.get("width")),
        )

    def to_json_data(self) -> Any:
        data = { "op": "acquire_pixel_buffer" }
        data["format"] = _to_json_data(self.format)
        data["height"] = _to_json_data(self.height)
        data["request_id"] = _to_json_data(self.request_id)
        data["width"] = _to_json_data(self.width)
        return data

@dataclass
class EscalateRequestAcquireTexture(EscalateRequest):
    format: 'str'
    """
    Texture format identifier. Lowercase snake-case names: rgba8_unorm,
    rgba8_unorm_srgb, bgra8_unorm, bgra8_unorm_srgb, rgba16_float, rgba32_float,
    nv12.
    """

    height: 'int'
    """
    Pixel height of the texture.
    """

    request_id: 'str'
    """
    Correlates request with response. UUID string.
    """

    usage: 'List[str]'
    """
    Usage flags the texture must support. Non-empty array of lowercase
    snake-case tokens drawn from: copy_src, copy_dst, texture_binding,
    storage_binding, render_attachment. Host validates — unknown tokens return
    an error response.
    """

    width: 'int'
    """
    Pixel width of the texture.
    """


    @classmethod
    def from_json_data(cls, data: Any) -> 'EscalateRequestAcquireTexture':
        return cls(
            "acquire_texture",
            _from_json_data(str, data.get("format")),
            _from_json_data(int, data.get("height")),
            _from_json_data(str, data.get("request_id")),
            _from_json_data(List[str], data.get("usage")),
            _from_json_data(int, data.get("width")),
        )

    def to_json_data(self) -> Any:
        data = { "op": "acquire_texture" }
        data["format"] = _to_json_data(self.format)
        data["height"] = _to_json_data(self.height)
        data["request_id"] = _to_json_data(self.request_id)
        data["usage"] = _to_json_data(self.usage)
        data["width"] = _to_json_data(self.width)
        return data

class EscalateRequestLogLevel(Enum):
    """
    Severity level of the record. Maps 1:1 onto tracing::Level.
    """

    DEBUG = "debug"
    ERROR = "error"
    INFO = "info"
    TRACE = "trace"
    WARN = "warn"
    @classmethod
    def from_json_data(cls, data: Any) -> 'EscalateRequestLogLevel':
        return cls(data)

    def to_json_data(self) -> Any:
        return self.value

class EscalateRequestLogSource(Enum):
    """
    Origin runtime of the record. Always "python" or "deno" on the wire — Rust
    never routes through escalate; Rust call sites hit `tracing::*!()` directly
    on the host.
    """

    DENO = "deno"
    PYTHON = "python"
    @classmethod
    def from_json_data(cls, data: Any) -> 'EscalateRequestLogSource':
        return cls(data)

    def to_json_data(self) -> Any:
        return self.value

@dataclass
class EscalateRequestLog(EscalateRequest):
    attrs: 'Dict[str, Any]'
    """
    User-supplied structured fields. Copied flat onto the emitted
    RuntimeLogEvent's `attrs` map — not nested under an `attrs.key` path in
    the JSONL.
    """

    channel: 'Optional[str]'
    """
    Interceptor channel when `intercepted: true`. Conventional values: "stdout",
    "stderr", "console.log", "logging", "fd1", "fd2". Null when `intercepted:
    false`.
    """

    intercepted: 'bool'
    """
    True when the record was captured from subprocess stdout/stderr,
    console.log, root logging handler, or a raw fd write, rather than a direct
    `streamlib.log.*` call.
    """

    level: 'EscalateRequestLogLevel'
    """
    Severity level of the record. Maps 1:1 onto tracing::Level.
    """

    message: 'str'
    """
    Primary human-readable message.
    """

    pipeline_id: 'Optional[str]'
    """
    Pipeline identifier. Null for runtime-level records.
    """

    processor_id: 'Optional[str]'
    """
    Processor identifier. Null outside a processor.
    """

    source: 'EscalateRequestLogSource'
    """
    Origin runtime of the record. Always "python" or "deno" on the wire — Rust
    never routes through escalate; Rust call sites hit `tracing::*!()` directly
    on the host.
    """

    source_seq: 'str'
    """
    Subprocess-monotonic sequence number (uint64 as string — JTD has no native
    u64). Escape hatch for recovering subprocess-local order within a single
    source. Not authoritative across sources — use `host_ts` for merged-stream
    ordering.
    """

    source_ts: 'str'
    """
    Subprocess wall-clock timestamp ISO8601 (advisory). Never used for ordering;
    the host stamps `host_ts` on receipt as the authoritative sort key.
    """


    @classmethod
    def from_json_data(cls, data: Any) -> 'EscalateRequestLog':
        return cls(
            "log",
            _from_json_data(Dict[str, Any], data.get("attrs")),
            _from_json_data(Optional[str], data.get("channel")),
            _from_json_data(bool, data.get("intercepted")),
            _from_json_data(EscalateRequestLogLevel, data.get("level")),
            _from_json_data(str, data.get("message")),
            _from_json_data(Optional[str], data.get("pipeline_id")),
            _from_json_data(Optional[str], data.get("processor_id")),
            _from_json_data(EscalateRequestLogSource, data.get("source")),
            _from_json_data(str, data.get("source_seq")),
            _from_json_data(str, data.get("source_ts")),
        )

    def to_json_data(self) -> Any:
        data = { "op": "log" }
        data["attrs"] = _to_json_data(self.attrs)
        data["channel"] = _to_json_data(self.channel)
        data["intercepted"] = _to_json_data(self.intercepted)
        data["level"] = _to_json_data(self.level)
        data["message"] = _to_json_data(self.message)
        data["pipeline_id"] = _to_json_data(self.pipeline_id)
        data["processor_id"] = _to_json_data(self.processor_id)
        data["source"] = _to_json_data(self.source)
        data["source_seq"] = _to_json_data(self.source_seq)
        data["source_ts"] = _to_json_data(self.source_ts)
        return data

@dataclass
class EscalateRequestReleaseHandle(EscalateRequest):
    handle_id: 'str'
    """
    Opaque handle ID previously returned by acquire_*.
    """

    request_id: 'str'
    """
    Correlates request with response. UUID string.
    """


    @classmethod
    def from_json_data(cls, data: Any) -> 'EscalateRequestReleaseHandle':
        return cls(
            "release_handle",
            _from_json_data(str, data.get("handle_id")),
            _from_json_data(str, data.get("request_id")),
        )

    def to_json_data(self) -> Any:
        data = { "op": "release_handle" }
        data["handle_id"] = _to_json_data(self.handle_id)
        data["request_id"] = _to_json_data(self.request_id)
        return data

def _from_json_data(cls: Any, data: Any) -> Any:
    if data is None or cls in [bool, int, float, str, object] or cls is Any:
        return data
    if cls is datetime:
        return _parse_rfc3339(data)
    if get_origin(cls) is Union:
        return _from_json_data(get_args(cls)[0], data)
    if get_origin(cls) is list:
        return [_from_json_data(get_args(cls)[0], d) for d in data]
    if get_origin(cls) is dict:
        return { k: _from_json_data(get_args(cls)[1], v) for k, v in data.items() }
    return cls.from_json_data(data)

def _to_json_data(data: Any) -> Any:
    if data is None or type(data) in [bool, int, float, str, object]:
        return data
    if type(data) is datetime:
        return data.isoformat()
    if type(data) is list:
        return [_to_json_data(d) for d in data]
    if type(data) is dict:
        return { k: _to_json_data(v) for k, v in data.items() }
    return data.to_json_data()

def _parse_rfc3339(s: str) -> datetime:
    datetime_re = '^(\d{4})-(\d{2})-(\d{2})[tT](\d{2}):(\d{2}):(\d{2})(\.\d+)?([zZ]|((\+|-)(\d{2}):(\d{2})))$'
    match = re.match(datetime_re, s)
    if not match:
        raise ValueError('Invalid RFC3339 date/time', s)

    (year, month, day, hour, minute, second, frac_seconds, offset,
     *tz) = match.groups()

    frac_seconds_parsed = None
    if frac_seconds:
        frac_seconds_parsed = int(float(frac_seconds) * 1_000_000)
    else:
        frac_seconds_parsed = 0

    tzinfo = None
    if offset == 'Z':
        tzinfo = timezone.utc
    else:
        hours = int(tz[2])
        minutes = int(tz[3])
        sign = 1 if tz[1] == '+' else -1

        if minutes not in range(60):
            raise ValueError('minute offset must be in 0..59')

        tzinfo = timezone(timedelta(minutes=sign * (60 * hours + minutes)))

    second_parsed = int(second)
    if second_parsed == 60:
        second_parsed = 59

    return datetime(int(year), int(month), int(day), int(hour), int(minute),
                    second_parsed, frac_seconds_parsed, tzinfo)            
