// Copyright (c) 2025 Jonathan Fontanez
// SPDX-License-Identifier: BUSL-1.1
//
// Generated from JTD schema using jtd-codegen. DO NOT EDIT.

// Code generated by jtd-codegen for TypeScript v0.2.1

/**
 * What to capture: Display, Window, or Application
 */
export enum ScreenCaptureConfigTargetType {
  Application = "Application",
  Display = "Display",
  Window = "Window",
}

/**
 * Configuration for screen capture using ScreenCaptureKit (macOS 12.3+)
 */
export interface ScreenCaptureConfig {
  /**
   * What to capture: Display, Window, or Application
   */
  target_type: ScreenCaptureConfigTargetType;

  /**
   * Bundle identifier for Application mode (e.g., 'com.apple.Safari')
   */
  app_bundle_id?: string;

  /**
   * Display index for Application mode (default: 0)
   */
  app_display_index?: number;

  /**
   * Display index for Display mode (default: 0 for main display)
   */
  display_index?: number;

  /**
   * Exclude current application from capture (default: true)
   */
  exclude_current_app?: boolean;

  /**
   * Target frame rate in fps (default: 30.0)
   */
  frame_rate?: number;

  /**
   * Whether to capture cursor (default: false)
   */
  show_cursor?: boolean;

  /**
   * Window ID for Window mode
   */
  window_id?: number;

  /**
   * Window title substring for Window mode
   */
  window_title?: string;
}
