// Copyright (c) 2025 Jonathan Fontanez
// SPDX-License-Identifier: BUSL-1.1
//
// Generated from JTD schema using jtd-codegen. DO NOT EDIT.

// Code generated by jtd-codegen for TypeScript v0.2.1

/**
 * Configuration for Linux MP4 video writing via ffmpeg encode + mux.
 */
export interface LinuxMp4writerConfig {
  /**
   * Fallback frame rate if not provided by upstream Videoframe.
   */
  fps: number;

  /**
   * Path to write the output MP4 file.
   */
  output_path: string;

  /**
   * Expected duration in seconds (for silent audio track length).
   */
  duration_secs?: number;
}
