// Copyright (c) 2025 Jonathan Fontanez
// SPDX-License-Identifier: BUSL-1.1
//
// Generated from JTD schema using jtd-codegen. DO NOT EDIT.

// Code generated by jtd-codegen for TypeScript v0.2.1

/**
 * Configuration for audio capture (macOS)
 */
export interface AudioCaptureConfig {
  /**
   * Audio input device name. If None, uses default device
   */
  device_id?: string;
}
