// Copyright (c) 2025 Jonathan Fontanez
// SPDX-License-Identifier: BUSL-1.1
//
// Generated from JTD schema using jtd-codegen. DO NOT EDIT.

// Code generated by jtd-codegen for TypeScript v0.2.1

/**
 * Polyglot subprocess escalate-on-behalf response (host → subprocess)
 */
export type EscalateResponse = EscalateResponseContended | EscalateResponseErr | EscalateResponseOk;

export interface EscalateResponseContended {
  result: "contended";

  /**
   * Correlates response with request. Returned by [`try_acquire_cpu_readback`]
   * (and any future `try_*` op that opts into the same shape) when the host's
   * adapter would have blocked on a competing reader/writer. The subprocess
   * gets no handle, no planes, and no surface-share registrations to release —
   * `contended` is purely advisory, the customer skips the frame and re-tries
   * later.
   */
  request_id: string;
}

export interface EscalateResponseErr {
  result: "err";

  /**
   * Human-readable error message from the host side.
   */
  message: string;

  /**
   * Correlates response with request.
   */
  request_id: string;
}

export interface EscalateResponseOkCpuReadbackPlane {
  /**
   * Plane bytes-per-pixel. BGRA/RGBA: 4. NV12 plane 0 (Y): 1. NV12 plane 1 (UV
   * interleaved): 2.
   */
  bytes_per_pixel: number;

  /**
   * Plane height in texels.
   */
  height: number;

  /**
   * Surface-share UUID for this plane's staging buffer.
   */
  staging_surface_id: string;

  /**
   * Plane width in texels.
   */
  width: number;
}

export interface EscalateResponseOk {
  result: "ok";

  /**
   * Opaque handle returned by the host. For acquire_pixel_buffer this is
   * the PixelBufferPoolId the host registered with its pixel-buffer pool and
   * SurfaceStore. For acquire_texture this is a host-side UUID keying the
   * EscalateHandleRegistry's texture slot. For release_handle this echoes the
   * released id.
   */
  handle_id: string;

  /**
   * Correlates response with request. Matches request_id in EscalateRequest.
   */
  request_id: string;

  /**
   * Per-plane staging-buffer descriptors set on `acquire_cpu_readback`
   * responses. Length equals `SurfaceFormat::plane_count` for the target
   * surface (1 for BGRA8/RGBA8, 2 for NV12). Each entry's `staging_surface_id`
   * can be `check_out`ed from the surface-share service to obtain a DMA-BUF FD
   * over the host-allocated staging `VulkanPixelBuffer` for that plane; mmap
   * that FD to read or write the plane's tightly-packed bytes (`width * height
   * * bytes_per_pixel` per plane).
   */
  cpu_readback_planes?: EscalateResponseOkCpuReadbackPlane[];

  /**
   * Resolved pixel or texture format identifier.
   */
  format?: string;

  /**
   * Height in pixels (set on acquire_pixel_buffer and acquire_texture
   * responses).
   */
  height?: number;

  /**
   * Resolved usage tokens (set on acquire_texture responses). Array reflects
   * the exact flags the host honored.
   */
  usage?: string[];

  /**
   * Width in pixels (set on acquire_pixel_buffer and acquire_texture
   * responses).
   */
  width?: number;
}
