// Copyright (c) 2025 Jonathan Fontanez
// SPDX-License-Identifier: BUSL-1.1
//
// Generated from JTD schema using jtd-codegen. DO NOT EDIT.

// Code generated by jtd-codegen for TypeScript v0.2.1

/**
 * Video frame for IPC - references GPU surface by ID
 */
export interface Videoframe {
  /**
   * Sequential frame counter (uint64 as string - parse to native uint64)
   */
  frame_index: string;

  /**
   * Frame height in pixels
   */
  height: number;

  /**
   * GPU surface ID (IOSurface on macOS)
   */
  surface_id: string;

  /**
   * Monotonic timestamp in nanoseconds (int64 as string - parse to native
   * int64)
   */
  timestamp_ns: string;

  /**
   * Frame width in pixels
   */
  width: number;
}
