// Copyright (c) 2025 Jonathan Fontanez
// SPDX-License-Identifier: BUSL-1.1
//
// Generated from JTD schema using jtd-codegen. DO NOT EDIT.

// Code generated by jtd-codegen for TypeScript v0.2.1

/**
 * Polyglot subprocess escalate-on-behalf request (subprocess → host)
 */
export type EscalateRequest =
  | EscalateRequestAcquirePixelBuffer
  | EscalateRequestAcquireTexture
  | EscalateRequestReleaseHandle;

export interface EscalateRequestAcquirePixelBuffer {
  op: "acquire_pixel_buffer";

  /**
   * Pixel format identifier (e.g. bgra32, nv12_video_range, gray8).
   */
  format: string;

  /**
   * Pixel height of the buffer.
   */
  height: number;

  /**
   * Correlates request with response. UUID string.
   */
  request_id: string;

  /**
   * Pixel width of the buffer.
   */
  width: number;
}

export interface EscalateRequestAcquireTexture {
  op: "acquire_texture";

  /**
   * Texture format identifier (rgba8_unorm, bgra8_unorm, rgba16_float, ...).
   */
  format: string;

  /**
   * Pixel height of the texture.
   */
  height: number;

  /**
   * Correlates request with response. UUID string.
   */
  request_id: string;

  /**
   * Usage tokens (copy_src, copy_dst, texture_binding, storage_binding,
   * render_attachment).
   */
  usage: string[];

  /**
   * Pixel width of the texture.
   */
  width: number;
}

export interface EscalateRequestReleaseHandle {
  op: "release_handle";

  /**
   * Opaque handle ID previously returned by acquire_*.
   */
  handle_id: string;

  /**
   * Correlates request with response. UUID string.
   */
  request_id: string;
}
