// Copyright (c) 2025 Jonathan Fontanez
// SPDX-License-Identifier: BUSL-1.1
//
// Generated from JTD schema using jtd-codegen. DO NOT EDIT.

// Code generated by jtd-codegen for TypeScript v0.2.1

/**
 * Configuration for camera capture (macOS/iOS)
 */
export interface CameraConfig {
  /**
   * Camera device unique ID. If None, uses default camera
   */
  device_id?: string;

  /**
   * Maximum frames per second (ceiling). If None, uses main display refresh
   * rate
   */
  max_fps?: number;

  /**
   * Minimum frames per second (floor). Default: 60.0
   */
  min_fps?: number;
}
