// Copyright (c) 2025 Jonathan Fontanez
// SPDX-License-Identifier: BUSL-1.1
//
// Generated from JTD schema using jtd-codegen. DO NOT EDIT.

// Code generated by jtd-codegen for TypeScript v0.2.1

/**
 * Configuration for video passthrough
 */
export interface SimplePassthroughConfig {
  /**
   * Scale factor for passthrough
   */
  scale: number;
}
