// Copyright (c) 2025 Jonathan Fontanez
// SPDX-License-Identifier: BUSL-1.1
//
// Generated from JTD schema using jtd-codegen. DO NOT EDIT.

// Code generated by jtd-codegen for TypeScript v0.2.1

/**
 * How video content is scaled within the window. Default: Letterbox
 */
export enum DisplayConfigScalingMode {
  Crop = "Crop",
  Letterbox = "Letterbox",
  Stretch = "Stretch",
}

/**
 * Configuration for video display window (macOS/iOS)
 */
export interface DisplayConfig {
  /**
   * Window height in pixels
   */
  height: number;

  /**
   * Window width in pixels
   */
  width: number;

  /**
   * Number of drawable buffers (2=double, 3=triple). Default: 2
   */
  drawable_count?: number;

  /**
   * How video content is scaled within the window. Default: Letterbox
   */
  scaling_mode?: DisplayConfigScalingMode;

  /**
   * Window title. Default: 'streamlib Display'
   */
  title?: string;

  /**
   * Enable vsync (synchronize to display refresh rate). Default: true
   */
  vsync?: boolean;
}
