// Copyright (c) 2025 Jonathan Fontanez
// SPDX-License-Identifier: BUSL-1.1
//
// Generated from JTD schema using jtd-codegen. DO NOT EDIT.

// Code generated by jtd-codegen for TypeScript v0.2.1

/**
 * Polyglot subprocess escalate-on-behalf response (host → subprocess)
 */
export type EscalateResponse = EscalateResponseContended | EscalateResponseErr | EscalateResponseOk;

export interface EscalateResponseContended {
  result: "contended";

  /**
   * Correlates response with request. Returned by [`try_acquire_cpu_readback`]
   * (and any future `try_*` op that opts into the same shape) when the host's
   * adapter would have blocked on a competing reader/writer. The subprocess
   * gets no handle, no planes, and no surface-share registrations to release —
   * `contended` is purely advisory, the customer skips the frame and re-tries
   * later.
   */
  request_id: string;
}

export interface EscalateResponseErr {
  result: "err";

  /**
   * Human-readable error message from the host side.
   */
  message: string;

  /**
   * Correlates response with request.
   */
  request_id: string;
}

export interface EscalateResponseOk {
  result: "ok";

  /**
   * Opaque handle returned by the host. For acquire_pixel_buffer this is
   * the PixelBufferPoolId the host registered with its pixel-buffer pool and
   * SurfaceStore. For acquire_texture this is a host-side UUID keying the
   * EscalateHandleRegistry's texture slot. For release_handle this echoes the
   * released id.
   */
  handle_id: string;

  /**
   * Correlates response with request. Matches request_id in EscalateRequest.
   */
  request_id: string;

  /**
   * Resolved pixel or texture format identifier.
   */
  format?: string;

  /**
   * Height in pixels (set on acquire_pixel_buffer and acquire_texture
   * responses).
   */
  height?: number;

  /**
   * Decimal-string-encoded u64 timeline value the host signaled on
   * the surface's shared timeline semaphore at end-of-submit. Set on
   * `run_cpu_readback_copy` and `try_run_cpu_readback_copy` responses. The
   * subprocess waits on its imported `ConsumerVulkanTimelineSemaphore` for this
   * value before reading or writing the staging buffer mapped at registration
   * time. JTD has no native u64 — wire form is decimal-string, parsed back to
   * u64 on the subprocess side.
   */
  timeline_value?: string;

  /**
   * Resolved usage tokens (set on acquire_texture responses). Array reflects
   * the exact flags the host honored.
   */
  usage?: string[];

  /**
   * Width in pixels (set on acquire_pixel_buffer and acquire_texture
   * responses).
   */
  width?: number;
}
