// Copyright (c) 2025 Jonathan Fontanez
// SPDX-License-Identifier: BUSL-1.1
//
// Generated from JTD schema using jtd-codegen. DO NOT EDIT.

// Code generated by jtd-codegen for TypeScript v0.2.1

/**
 * Mixing strategy for combining signals
 */
export enum AudioMixerConfigStrategy {
  Sum = "Sum",
  SumClipped = "SumClipped",
  SumNormalized = "SumNormalized",
}

/**
 * Configuration for mixing two mono signals into stereo
 */
export interface AudioMixerConfig {
  /**
   * Mixing strategy for combining signals
   */
  strategy: AudioMixerConfigStrategy;
}
